### ISSUE TITLE
JC ❤️  #pixelscamp #forever

### ISSUE THREAD

**Issue by jpgcc** [PixelsCamp/pixelscamp-forever#10]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt.

This is my public proof on social media:

[https://twitter.com/jpgcc_/status/1305461101832871936](https://twitter.com/jpgcc_/status/1305461101832871936)

### Encrypted Name and Shipping Address:

```
U2FsdGVkX1/nH7IRwtBPQ9fL+lgvepmHTMO6fQhdYRRvAj0eqzOXXl6lcwN6HpRa8jN+xrnPFIoUs4Pu0ugetNhWP/mt8q4UTPYSYnycI35vkybFnqVG5gBfoTXa0+uL
```

### Encrypted Shared Key:

```
kcmr8emgpYx77lv5K/mbd/cFSWW8vOX6vgo7sJkUO3dOV/d2BblSZEYo88R1lYcQQ+NI9bQGuUsy28Pd0X6FRTK/debAYvkjrrbvbPAxJ9kMMdnW8kVKpD3q5Z1gyCSqod7av6dIFj9fqirrguR7F3cbP5KtT7f0tSY6HkZXRGPIQO0wN3nuG4RLD7Kxly1tJqDDcs+OxvyiWHjskTcemTVrTiA+ZoAc+squbWjTrJvb40oT/MqwbmqRt5IyhBydhxnoKnaxr4Tds70y1ypK0YlwJAwnwliz+kHCezYM4nPKxePiAIoFbZtMgKb11FPsNWnEFdX3191lUuawUH25I1oLSXEacQ7RxCp0jQTcvxXScLznnm1fvrzowu+46U/IkjoBdMi4wGF+TFSeaHgCjb4eJSlcesaeyTfxWaJCGfSV9DwZRvtz2fOGJmezTRTrfIfJsX0YXeP8s4PNvbD4jP9sxpxC3jt3rat0mtAG8QRnqvCbnYYQUrV9msnvFpvit8O49yPCkctsieaUXghVPCGhh92HWIoAa2BV1vfLMub9RPf26VVl89c4QdkVs7lTldZfq5nvhlkqkGQ3yr0oEc7oBQK2iutOLjRjWoM1Cw2SlK8Ews2ySkzhfE935bQJgaPBrscxVpS9BpKWsYPb/3sXU2bM0bluaClUSkoTQSU=
```

**Comment by carlosefr** [comment]
Hi @jpgcc 

Can you please regenerate both encrypted bits using the updated information in the README? The initial public key was wrong and has been replaced with the correct key, plus the OpenSSL commands were updated to ensure (some) compatibility between versions.

Sorry about the trouble.

**PS:** If you have a preference for t-shirt size, we'll try to honor it if we can.

**Comment by jpgcc** [comment]
@carlosefr Done. If that's the case, I'd prefer an **M** please. Thanks :-)

**Comment by carlosefr** [comment]
Hi @jpgcc,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to org@pixels.camp. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (carlosefr) on the Pixels Camp Slack.

**Comment by jpgcc** [comment]
Arrived (can't seem to add the label myself)
