### ISSUE TITLE
To the moon 🚀

### ISSUE THREAD

**Issue by ickas** [PixelsCamp/pixelscamp-forever#11]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt.

This is my public proof on social media:

[Sad to know that @pixelscamp 4.0 has been cancelled! But always proud to be part of this community ✊
#pixelscamp #forever 
@ Twitter](https://twitter.com/henrikemacedo/status/1305461638997434370?s=21)

### Encrypted Name and Shipping Address:

```
U2FsdGVkX19q5RQg9V6RQUaqKYhy0xWGP6SbnuSXoZcV863Pnh8DqGvU/VeZiM7ZcAMgF19q96oPyxmmUWNzIGBUojIyXIwuP6hA6F7Q5xIlITqjkHSH/aumgK7FskecWUQc4izrFQoopA6jB9A9cw==
```

### Encrypted Shared Key:

```
HBPWEVmImBh/y/8FfpHlIPPsr1Ptnl1FCA6Lf/4oSrDrqmHw2B1viEhE2GYsgUZSQiLMGCgxtS35CsIdnZjYGIvNawUPWG38SKRb0Zgw0cTYdBn83aw/8uaNyOOwLGBLBCQtuubvFs1RD9DbxdqgPdisVYhJP5gAl3Ge00JaXCnehNXovRPhx61eptoKGAuUNWNza/BchiFd1DbpUxwpMr9tkAp8R6kfoREAYcnZ8GcIMIJj8p/c1Fpfcl9tuVU+c+sBg8o/YxbVp1obi7GZA+Ou5X4lRq/XQ9GcmfAAAWXKx99Zt1rWcZDnIcjGoVitN5/x6O4nOem5InDh6jpPv54Zoaym6L8pHCOLUTAV1wHl0eXJ9s142MwcHG/BHTAtospeKetYF0/dW1c0F7x2/+iTgacnYPHCaFUiuWFF1n3uG3f2zTS7DumfbZ8/8On9evUz20IObMLhtoqUWl4GCpVazwH2A5Ebcnbz39s7pZl127dcuajhuC4OXbi0I/UgIYikp9wDgsGFT09XlvSpKqgHjgFraSEcD1cucEoQfIMgX28MICOU8grQNoePL3Uei2eIM0T2AkCsXBTJqaV1nemOz5w5nJA6UFvCaOLbq8kk4g0sFImRyIgmXQz5jnpMTaXuOMENmC2mR676qP/HXXt0PwJ3XnrZajPrtghfYiE=
```

**Comment by carlosefr** [comment]
Hi @henriquemacedo 

Can you please regenerate both encrypted bits using the updated information in the README? The initial public key was wrong and has been replaced with the correct key, plus the OpenSSL commands were updated to ensure (some) compatibility between versions.

Sorry about the trouble.

**PS:** If you have a preference for t-shirt size, we'll try to honor it if we can.

**Comment by ickas** [comment]
Hey @carlosefr 👋

I have updated the information above.
About the t-shirt, size L 🤞

**Comment by carlosefr** [comment]
Hi @henriquemacedo ,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to org@pixels.camp. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (carlosefr) on the Pixels Camp Slack.
