### ISSUE TITLE
I talk a lot :)

### ISSUE THREAD

**Issue by luisfcorreia** [PixelsCamp/pixelscamp-forever#12]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt.

This is my public proof on social media:

https://twitter.com/LuisFCorreia/status/1305460354110164992

### Encrypted Name and Shipping Address:

U2FsdGVkX18gpyzF7yPOPZCbrnAE9YoJW2f1CInsWywTB2M30hrDSoU6A7WD284WxEHFpLE4UZnF
hopL5cc5LscxUcYoW5LicFG1PQflhcU=

### Encrypted Shared Key:

epy2vKL5hkWWKbgTLV1+GGjqEUtOc55kGN4ElYGVZhMhlW4FzPXzXfk4U7cKjM7GnVfwd040mnd6
Uak7PepXx4RbmS5xbHn3cJJ4EV3INLZ7uzAN3Bqy+nCbRNUd38ygYoL5o7mDxxV92thL+twN6LOG
1Rdg4H3hhSOaYFNBA8fU57JLAx0o65a+UnwhsHvB6JZZmLK2lxcBlCLZWk3GeckRS9hSmEY4ls8v
QJdsZtQVfZefWL2jldLy0td3KDwVJqn82Q7TwpMx7KCFLNdMRzBbZB+kzV8ZaQuLTMnaGfI5vFTR
qg2XzdFSTBqmB4XHpW7rvwd1Q7gykTeeQ1n5BaNQCWuiljnrPkbvHrmfYkSmT2pDejP8kg3TJjlc
aMk6X86A4APWsSKuoxbwCopq720ILSmW8I+dXlGL78tYw+mn72dwBRTxEJQW6Tg1h6zDw6dpfAhu
Dp6pLKWIw81EB89oHLVlpAeCaTb4sPWFVdwyDCA2L1enCzzGHNMsaUP4UqkOugy20IDXH8u/q2vg
s1iSrTJT2qEI56G7RrapwY7PFXHVa+Jq5cbDPedPdsv+QpCp6grFN5yaNxV0oqIoTBaurCofahYm
98OhFJG+7OqLufLCe2R1EGedQPxzZA4BM9AZfjwc7EZu2p2erI27wWH9tKCGPSM5YTewNVFqvxw=

(followed all instructions available at 14:00 2020-09-14)

**Comment by luisfcorreia** [comment]
now with fresh keys

**Comment by carlosefr** [comment]
If you have a preference for t-shirt size, we'll try to honor it if we can.

**Comment by luisfcorreia** [comment]
XL if possible

**Comment by carlosefr** [comment]
Hi @luisfcorreia ,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to org@pixels.camp. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (carlosefr) on the Pixels Camp Slack.
