### ISSUE TITLE
🏆 #pixelscamp #forever #oneofus

### ISSUE THREAD

**Issue by tofran** [PixelsCamp/pixelscamp-forever#13]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt.

This is my public proof on social media:

https://twitter.com/tofran_/status/1305461795986046976

![2020-09-14_12:04:57](https://user-images.githubusercontent.com/5692603/93078527-896c9f00-f682-11ea-9a4c-287dca9be0e9.png)

### Encrypted Name and Shipping Address:

```
U2FsdGVkX1/v6wHaTLwMRysZO9jWLRyUYIrugV0J+tyr2B4hhALX9l6PJhvLtznRX4xGmRM5pHlh
9AUiP/3KmzHiTZ2BQb9mvfut6m3+7TM=
```

### Encrypted Shared Key:

```
qLnoTCqYLLLwgUbp64jnZAflvU9QfnUndLo0/FVZZrv2hZ5wCnCkzyv9+wZ4cWTkFtQidIB4TcZE
acMOL5QKtAYxXpIWS1T67uWJz72Dhlci7rpN3JM6nWt23WSTB7IVaTZdH0cDjOjLZBg6NIiArUlK
2v+MxxYmAVkRwR8zQCsRBlRhFo9eThDjGrHPTbX9M8DydhF7rXRAXj5JEIB7DJ2L3FRzJwglo61Q
nZMZ8LvhjH61mnOsX15iBMIoAXzDVhLf3KpvSDBIDIjxKyCAPgvW1LbDBIfCNVGwf/3lZjY2LZw5
VmjyuqB5A5Nw6BFP2s+WQcdNn/gjsoeDmMWaNg==
```

_You can edit the issue and paste the encrypted bits later if you wish. They're only needed after the request is accepted._

👕 Size
   US: S
   EU: M

**Comment by tofran** [comment]
Since the`public.crt` changed, here's the new shipping data

### Encrypted Name and Shipping Address:

```
U2FsdGVkX1+Xu53uC++wjtpaRW7ezxeLERxMbZ5x3d9yU8BAKHgxImxDBfMjy844LcU+eM7X5M4L
G3bSUU/BbqC+C6LtLnoZjNZJLkgzh1k=
```

### Encrypted Shared Key:

```
vNWQ4ZRvXrup3YjYzXM9riXnVYr27a05ZcDGcRSb8V1cQOXFMdydSHh6R59l0DYPvsiL233MoRGb
pkLt+A+YTBrIKz1UjbVOAXaSXbRfWeqS5lK4iX9y6dRmNE4sWzWpum74Xbg91QWaFtRjWzU2eMJl
sY5/YzpIhOXGkPa4BQ7wMNAgrEzfiJXmVYubUcmJCouhxVgEMNU2lXrVpPmeG69vM2Vg7i2psxEr
47XRQjJWJiE47YjiaUTLn/UAR+5O0l7iNo3+AnoQwBHbm9PiFt82qQmV+QMMxbp/4yjCZvnMVSQQ
X2ykKLll6xWp6/Al5JoKtQ13P7kkdKBUIBgkQLCVk0gFi8yY/NfWdoVZK1vibXg62WY4wmWm8B/G
fRTZGM54BQer7CMg4AqzJgzndpJuReugsdQcGAIJscMg9UFDAoD0p2YjzuHcipfU8F/8VNyTuoXS
U2BoSpFTsKi0UlPEASvwh/9K7xe135KKNRRVQgMciA+aotPgiTIpTqzPsKR//L/Xt7lxRPXQpfOg
UPsyfsojprpi47XmlsRFhF8C2uN8dnUSvVNvNJ5xTTLER9WRq1oA1xT/NI7N6N3lrpsq/4ODfprv
kclWUNjHmTIonfwbSWMIOeWjJPPqSBSe/7y8FlN+1tQGaUz/1AiaZSx3BAX4LYCrP5O/Oi7T6fg=
```

**Comment by carlosefr** [comment]
Hi @tofran,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to org@pixels.camp. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (carlosefr) on the Pixels Camp Slack.
