### ISSUE TITLE
#pixels camp #forever! :D

### ISSUE THREAD

**Issue by xRuiAlves** [PixelsCamp/pixelscamp-forever#14]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt.

This is my public proof on social media:

https://twitter.com/xRuiAlves/status/1305464107643088896?s=20
https://twitter.com/xRuiAlves/status/1305466619834109952?s=20

### Encrypted Name and Shipping Address:

```
U2FsdGVkX18qbgkk3ngBAJ7WnEXOwzFtg3j4txph49uBEvE9dSq5A3e9RtuGwiyc3bqmXtonfhfE
qLte6AzJ91OVCb1Ulqer+iSjBjLkzxqe0fSCvVliwhlv/GEMvadefK5FXP0gff8ri2pXZ58oe9Oi
CF/LQPY6ZhVp6E30kq/fyLPKUnltaMJffPKxOSfTRINEX9LhTbaT0WZ2x4Bq4Q==
```

### Encrypted Shared Key:

```
a5jU0uI0DMJebiw5WjgfBC9GMU2cyXRppwlwayrAX/F8WJZ+aofMOa1QyGrchRKLuUvM2SXCm6y5
V2JniRWMkjfVWDXlJx4sj94RtX4b6jkMD/h5bbVsP9XtUqJJ0QR+sBKvs2QZIu3dYjNRzHNWbRGE
Nfpv0GX/olYUisXAVZeLXJAaZdCx2Kg7Wpc3LuvFKO4uaOA14nodlKpu/u5e/o+lJuQEvX7/S7tn
9q/Tjtll4bb0HjQJOlSQBrRFXS/aUPxYcg0U14hSwAd9WbykeNjw6fnpfd4a5VKn1a69rMvXwHA0
Ge/v33gvkd2pF99eLMPRjz/JtiSFz9FqAy+vmvZEvDS77IdTSIrVu1sTGWEhuRcPddAsRK73weWH
mgDUGm8jolcnNVNeF8UY8uDC/0TqK1NBMQl8yg7CdqxryLyo35rFFv65BZtuT/1bFDpe5ynHytN2
pV67clKJab6dpwHOFjeDaebtP+w04WD/6cIUDbEadwLuMpdwXEXeA338kR1yPMjxRnJlwkp2GKer
jAxD92AX/8/ETCOvIaIgRuFNV7uB0q4N1XqgUZzw+xpC0dwahubJvEIJonESLXwq1JK49Gl/AyTP
jU9yaF0EOSNHzUuMql+AWAK9ndjdMgiVCbNhgbDXmOaITcSKJbu/Y+UKUk74eKAKB8V9jYkBIYs=
```

**Comment by carlosefr** [comment]
Hi @xRuiAlves 

Can you please regenerate both encrypted bits using the updated information in the README? The initial public key was wrong and has been replaced with the correct key, plus the OpenSSL commands were updated to ensure (some) compatibility between versions.

Sorry about the trouble.

**PS:** If you have a preference for t-shirt size, we'll try to honor it if we can.

**Comment by xRuiAlves** [comment]
Hello @carlosefr ! Thank you for the letting me know about the updates :+1: 

I've updated my issue as requested.

Regarding the t-shirt size, I would prefer an **M** if possible (if that's not feasible, I would rather have an **L** than an **S** if possible :sweat_smile:)

Cheers!

**Comment by carlosefr** [comment]
Hi @xRuiAlves ,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to org@pixels.camp. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (carlosefr) on the Pixels Camp Slack.

**Comment by xRuiAlves** [comment]
Hey @carlosefr !

Thank you for reaching out! I've sent my phone number by email, as requested 👍 

Cheers!
