### ISSUE TITLE
#pixelscamp #forever

### ISSUE THREAD

**Issue by jcazevedo** [PixelsCamp/pixelscamp-forever#15]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt in size L.

This is my public proof on social media:

https://twitter.com/jcazevedo/status/1305465361173753857

### Encrypted Name and Shipping Address:

```
U2FsdGVkX18a0/I2Op/m7coxmj7wSbVg4N0Jj/hNjkRmEAoAMckdsmJ/6wNIADY19mmQZ39mLRcYRkWRJUURSPD6J75yHz2CeNHpgZwbeQgB/0rYAnpvPKp5hx+Tb0Essjy7s7kp4hWig1vlTLk2xn8EW11HT9VS/urDSi63CKY=
```

### Encrypted Shared Key:

```
YDcjgjNvlMok1A7o9PkzQxOWsiC/5RtCcscgnVbgqn9N8ILOzhxO1T5RU0ZzBJu/RkO8YkAm7jrJNRUDW7bqp9hXSa/hF5v4sf7I3kmXLvIbZFmHrBH83TGGWB/cuRlS+mQRzYdSidPuxajQ2Q2fTIVapJB462I7M51Vq4Ssgs9y4y1IKOXdVDcZa/Xu/2CyRpAJTzX4e8G1g0i/CLAYmq4ajK4ON3HPDoVstSoOYAW+b++7BdzX3ehncQwV++/oVNoKv4hKGw1jLe2t/lfM7ZlvxTmSjBBXZTbXa0raRjy03HtF9sYiUzC5Sb8k/elj9YsxwJ1/XTqxFTccFk+WSgZqN6C86Izoi0mct2frmmIHsCYNZytsEB/Unjf+RIFUEaZ+W6QoF9Arn3e+0D+bED9US2MsXhf58V24qERXVfOKagd+yNjyYV+lJ7UTbJT7R6kJp/e52OEWRxzz5Wphg3AhtFsUIrDJqylOrbJXPn8oaSH/3Mw2tTkcIq7hM/coh1h3hmfIkwjWRg8KfzNHyxOTlRPSIDfimlV5fsevT3pVdunKnztnrS5N2/D6eWxHcSfuG7vH2mb9mvkloqUkj5XE6dvqYPavYwu/snVqGdx9s519k2B/NvsHcFPzR1ojqaVzub2PPgG3kRObYC317nG5JaEBhtz9NhSG9j8M2KA=
```

**Comment by carlosefr** [comment]
If you have a preference for t-shirt size, we'll try to honor it if we can.

**Comment by carlosefr** [comment]
Hi @jcazevedo ,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to org@pixels.camp. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (carlosefr) on the Pixels Camp Slack.

**Comment by jcazevedo** [comment]
@carlosefr: Messaged you on Slack. Thanks!

**Comment by jcazevedo** [comment]
@carlosefr: I confirm it has arrived, in case you want to update the issue labels.

Thank you!
