### ISSUE TITLE
Pixels Camp For Ever  💻 💪

### ISSUE THREAD

**Issue by mstrlaw** [PixelsCamp/pixelscamp-forever#16]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt.

[This is my public proof on social media](https://twitter.com/mstrlaw/status/1305464376145711105?s=20).

### Encrypted Name and Shipping Address:

```
U2FsdGVkX18QfDn7c4kAVsagfwLz03IEeqsouaA+3L7rSUkQHyMHVE2zcBKMDl0kq8ljPZsZjF4CkPUG20cr5LYZrn9CLBBxdNgQjVCmOFseY1X/PnocCmlziFqgVfCd
```

### Encrypted Shared Key:

```
k4bk287M41Mb65LdQT4rKC6g7+KK7rOmOz9ty5A+2j46FFF+YdW2LatkcZBsh/gfX9E83UX+h6W0ktIZjYHalrO0B4OmjhJtjmwJ2OQuRiSTiCBDdiptLg7VmJN/8IqG6c/LsZMDa94QxAyTjrIvnTcwjSjw9pyyT2tjqwlZxuFAPr73JbuC3egBHKIH4V1dSikvqzqd5Lm2P1yyztDxPWj7zmAntHnCxCVdEiVKjB353Py9iYF9cNewk5KHJEJHJW8xLsiMGEvvLdFuo+oUfXPV6StbTc2FDD9jVm3v8/zeO+KuxB54tzCgX1TqorS2C2dhyQ5NjY+tEViJAMCujXex+BlSmMGOxR38YXc/36UdnjNO4mFFHUHzbs1tmC+VB22MZLVxW9kORJBUA/GuL9eTP7bAJ0ZQBv2MdiCAVcvDrEf8X86SeriMSw9ab5sjVGDvw64j9zUA/ffl+dWmKXpMRQOOLkmUW47LzlBRY/RIFXixo6fwOtlOBs4B8CMY99wjvNQe/czX3/DF+xF/iPT/E8Fy3CpcTlkikkY+l3baOZBULP1hfhMPb3P8Nx/h+/oCdWHfIaQhAS7AQIuc1NL98urMropFTTWdgMsKiMpgCZ5LIdlqN3peWjkE0+0sODUiQAsZ3zNX36ErBkrVl/TIfqQDAzmfKratl4ej/ak=
```

**Comment by carlosefr** [comment]
Hi @mstrlaw 

Can you please regenerate both encrypted bits using the updated information in the README? The initial public key was wrong and has been replaced with the correct key, plus the OpenSSL commands were updated to ensure (some) compatibility between versions.

Sorry about the trouble.

**PS:** If you have a preference for t-shirt size, we'll try to honor it if we can.

**Comment by mstrlaw** [comment]
Done 👌 
**PS**: shirt size _M_ if possible.

**Comment by carlosefr** [comment]
Hi @mstrlaw ,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to org@pixels.camp. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (carlosefr) on the Pixels Camp Slack.
