### ISSUE TITLE
#pixelscamp #forever

### ISSUE THREAD

**Issue by lldh** [PixelsCamp/pixelscamp-forever#17]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt.

This is my public proof on social media (I'm the pretty in yellow :)):

**https://twitter.com/sunset_believer/status/1305469991224070144**

### Encrypted Name and Shipping Address:

```
U2FsdGVkX1/FGSUzrWK9ly1uBodEzVA2qJOn0gBuviuq8z6kFh0oX+vmnCzPxq1H7WoVO0ra0b+aCvrj2ZtgIdYRYokWSk2fugQxT5Ae733XhvKXISNYhgX/58NQ6QHTYOv4qIGd7DRcXWx8YZ+Nrw==
```

### Encrypted Shared Key:

```
v+WzjxyfJAZsto+ql53hpEj+n/Uw7YI3GBF/xYr0McC9GJPR5lZtIbxPQCHV1Cr797hJnzJew1iDMc5wsEktqHoKZkGwqMS4hc9F4VP+e0Y3kv6M+Edtr2ep5C05ahdIIyaJC3xUz5G7C5rn6lB1/r37XOPhwgVA4YCqAv9Em1cAqzqjIrMOG1SoZ5Bo36VnaA3Ik9If0hsraE42e1mJP1orpuozOTK8u+Kt0Ld+myPNk9mt5kTCuX+bpEWuFdYxnR0xtPqdAYjWWQUzCS/65VGB/4Olwg8lsLpKqwLc7p4HL2ZyFaw9qoehrmVqc5k7yZQ9xHFkzy7EQK0LHJWgRpbj6++g1lE5DVHe4ZYwbLvFKBY4p8hFXXaN83HZqjqkZecgHzWBIUcS7y4V3HBNReabeR2cZ0/RzHg49vJJsY/MPrw41rPzifGnBmPidwkkyXxGGMuHQUowguqt4Xz1SNdroLX6kw9BkKMbyY3CSLpkTZZer3aZE99JV5/wl59sGTELCcNf2sKkSv0ltTHvBelIUew6SdrxOdrSZrbjB6uYmyYEf1KYC0+XKzy5x+5OOrB/yH9toUW6EHILSNZxHgoeIv9uucwf4ZlOiZ2dnP/fS9No3RB7I9jsenK3vqsRAqCuB7akpkXp5O4SVl1TuwdIZxk9BgrsUtImLH4yBes=
```

**Comment by carlosefr** [comment]
Hi @lldh 

Can you please regenerate both encrypted bits using the updated information in the README? The initial public key was wrong and has been replaced with the correct key, plus the OpenSSL commands were updated to ensure (some) compatibility between versions.

Sorry about the trouble.

**PS:** If you have a preference for t-shirt size, we'll try to honor it if we can.

**Comment by lldh** [comment]
Done. 

As for 👕 size I would like a **L** if you have it. 
Thanks!

**Comment by carlosefr** [comment]
Hi @lldh,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to org@pixels.camp. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (carlosefr) on the Pixels Camp Slack.

**Comment by lldh** [comment]
Hi @carlosefr, I messaged you directly on slack. Thanks!
