### ISSUE TITLE
Roadtrip down memory lane on #forever #pixelscamp

### ISSUE THREAD

**Issue by martinhoaragao** [PixelsCamp/pixelscamp-forever#18]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt.

This is my public proof on social media: 

https://twitter.com/martinhoaragao/status/1305473343148220416
First pic - right side. Other two, Around the banner. 😅 We were able to grab Celso on Pixels.Camp 2.0 and he is right next to me. 

### Encrypted Name and Shipping Address:

```
U2FsdGVkX19UZpGb/QOKhXjwiiW4tO8Qy0dSowLc8sRHEj8nMstiZg6Qa340F4JpY71hm5Et0A80VO/TafNaTgbYJLcLgOg9ANorLJDqTIt5C4G0/CdV2G9VGFm8va6R
```

### Encrypted Shared Key:

```
EyKnWPwOXG2zHsw87msUXPaHlVVyCA3+2AeNq/FLNwLWUxjAq22g/xqmlZ0b3F7N/0FRAimXJ+5wUrSsjtBdaVKkoCkAung0tzL+3dU/cu/BlBdIPebWHBePb9uY36E15fvWHtyYb34a8m2LhCylJCxGgSy0c/vWXmPyZ2nWhx7N62X5Fk/ndwX+gfNRY9oWosSyovLb/Bee4rr66g12j0/QXnHTo744Mf5XVVtFnoYrXLDAarptYDa3YWufFCLBGc2KdHHZXKe+r50Kgy+dKzktvos50QXy1GPwNwQr0aG0uASYFGLyuMoYc2byfJ7/+aZFLyN4rXhEFrJWGUFaWMoMSRxTyKkMBjHKGDmUYzwTrdOrOnGgOVTaZ+xOCgGBA013KgLU3W11Ek6zBPK4degEJ9j4qDemyowkvp1I/1E4QgeqqJLC7Ij0ud4hYfvrX/mv0H/91Cu41rFEMAsgONSlXXZHbEAvNmLckbXiXbB8FyQdPSe2CkToa6eRRYKeaZua7c9dqlQN4H07j9pjHQ+CBY5Ul0aqnkHpVIoE1YTKrvATKTa6jYc4j95yjyyviO9P7skMFqxHMJpUm/pkVJTEW6psQGNgXk0UUB3g0QQGTqLLYCRkN21YJdSQsCbUNtJCfFIWeH1HWwh7L6dlyAwlXTFyDIxf9BnTySnQVOs=

```

**Comment by carlosefr** [comment]
Hi @martinhoaragao 

Can you please regenerate both encrypted bits using the updated information in the README? The initial public key was wrong and has been replaced with the correct key, plus the OpenSSL commands were updated to ensure (some) compatibility between versions.

Sorry about the trouble.

**PS:** If you have a preference for t-shirt size, we'll try to honor it if we can.

**Comment by martinhoaragao** [comment]
Updated! 

I prefer S 😅

**Comment by carlosefr** [comment]
Hi @martinhoaragao ,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to org@pixels.camp. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (carlosefr) on the Pixels Camp Slack.
