### ISSUE TITLE
I'm one of us! :tada:

### ISSUE THREAD

**Issue by abacao** [PixelsCamp/pixelscamp-forever#2]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt.

This is my public proof on social media:

https://twitter.com/Andr3Baca0/status/1305452788877594625

### Encrypted Name and Shipping Address:

```
U2FsdGVkX19qPqCoTw+6sI0jnfHrzvEVGb5nDCN4yHPiPdUocyObFCCXS++njYZbmdU9VFiFMUEi
JZM9LRl3xdAZiaZ0FLbxhG1OA0fddM8=
```

### Encrypted Shared Key:

```
vEBauWcib+GFOCtQkimvmEr/P6/t1Rsoys13kSBjP6TMrgHM5OYIbk0hOI+YW43dd4XrmZTt0oFQ
UAoPMFKERe/30YQWzKxTbr/V3W408k6aM/DL6GOwaWJ26ZvK+R11/QDATwa91cTR2upONVecIzw5
Z0xQiMnOv0LkTO/umuKBkqAA83/9q6g3gWpblj0Ecp80FpgGeGJcZ5F4b6LB69MM+2ISRd07AlqR
ndl+gxpaWEMFIiJkyWRXn7Q9Cu0uzSSfXA5NTB7u4ZxZL8TfgVKDPuKVqx9z2ayGt0G8mnphjSO7
k82JFI6mWAABsHSv5oGp0eRMNq9t16PyXynq1myB/08XGa7A3V6LdMmrkvpGCvVD+MVkDsL87ilt
7wmjEZYJtuR1O2WkCtOvOVpVrNQTq+DPtCuOVjNHSV6wTDiy4TDEKjessR3HnTI90Ma0wmg6fzj/
bI/okbaMUYlfUBbw1OMUBHY8pNuyD/wBDn0k6QU+3h5c5jFoYwAMFNzIl46kQl/qj6de+/bLBngz
MwByw3a1vJ0aBGE4KsyxFElK/ylDTZ51ggu/yvsrRUIHbvz32b1G3obtSm7Q5KX6TUJ2GQrihzDC
l6s+C72BfjO+d6aE6cYyXGbalBp9lHyzFgmwdW0D+NJ/sZziQA61gNAxv+Nu/5CrUffJ7iSA/OE=
```

_You can edit the issue and paste the encrypted bits later if you wish. They're only needed after the request is accepted._

**Comment by carlosefr** [comment]
Hi @abacao

Can you please regenerate both encrypted bits using the updated information in the README? The initial public key was wrong and has been replaced with the correct key, plus the OpenSSL commands were updated to ensure (some) compatibility between versions.

Sorry about the trouble. That's all it's missing.

**Comment by carlosefr** [comment]
Oh, and if you have a preference for the t-shirt size, we'll try to honor it if we can.

**Comment by abacao** [comment]
Hello @carlosefr 
I have updated the information on the issue.

Size M, if not possible, L.

**Comment by carlosefr** [comment]
Hi @abacao ,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to org@pixels.camp. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (carlosefr) on the Pixels Camp Slack.

**Comment by abacao** [comment]
@carlosefr Can mark as arrived! :bow:
