### ISSUE TITLE
Can you spare a shirt?

### ISSUE THREAD

**Issue by JD557** [PixelsCamp/pixelscamp-forever#21]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt.

This is my public proof on social media: https://twitter.com/JD557/status/1305482913090277376

### Encrypted Name and Shipping Address:

```
U2FsdGVkX1+GB0eM+DWGvfmaEDHElBIj0OKIujHaVD4s6zRDHj8vh3dml6pAM6XIP0gxZVkmG2rQDJ7G2IGREOrfGtHmMogKmAOtrYzNNQ7AS0Y7xcfC8zF0zZL6vx75KLwB/O0ZCc3unRf1oVnb/eGXnYgIU52zxjxQxN1qBYGi9DGXUainCR+vhhElSm7Z
```

### Encrypted Shared Key:

```
ZtkonIFEWzJXttIZhYQfewH9bFvKOw1mHTwduA/ZqzK9t41f+ciy6W/tbi0387hbdAZdcZIBHYoSTp6ypchmQJKUA3xTvcDI+Fh5HbPW67S07lwVpa4bpJIe5woo2IGqK2FCKy5jD2hGKHvcChotSIe4NYQf6SRZDnhlPo8Wctpx46fb3wyVgjr2sQjATDy0QLBoqudJ70hIMUIHeib6rfNWJ/naj8e1iZDYyfOnWQfaWPbH/T9CM4IqDenNfwgy7f+mDJe/HhoNyDWlLF+obNu8ok3fgKrNQ3gYlq53heteq+SN4czPyKcdpf9yLfJzPEoVV+El/M0ARkL0QoGLSh5Eiy20vZCXM+uofFh5sKgpwheZKOWQaHKRb7VtT9hmba8E6/18dUTF81225h7yqJ4MIMMy4d2lNCvCMqd+kae7u2+fL6BkXVv+6gfL6SNP/t84wXu4pE5Gi+s8Gnuj9fxKdhvU0mdC9dvnOGPm/LbrGyRvtU8inn0hqIbSZemF5QM5oyjVyQL7JyIHoNcxOCRJ6WzdA7+vXUgVKdfd0GPpxqXTKpeH2v08AJtWlgrvU3y29LUwYwTOrWCW8kVW1TO3xtdaT1yhtwjo9o+2Oya8WKrrn26eJbWR6H0bZT/+U0OculsIkQu1e4ubE1+U52RcW5I1n2gQ8Lxz9eg4v88=
```

**Comment by carlosefr** [comment]
Hi @JD557 

Can you please regenerate both encrypted bits using the updated information in the README? The initial public key was wrong and has been replaced with the correct key, plus the OpenSSL commands were updated to ensure (some) compatibility between versions.

Sorry about the trouble.

**PS:** If you have a preference for t-shirt size, we'll try to honor it if we can.

**Comment by JD557** [comment]
>Can you please regenerate both encrypted bits using the updated information in the README? 

Sure, updated.

>The initial public key was wrong and has been replaced with the correct key

As tradition mandates, the first public key shared is always either incorrect or the private key is lost 😅 

>PS: If you have a preference for t-shirt size, we'll try to honor it if we can.

Added the t-shirt size in the encrypted file.

**Comment by carlosefr** [comment]
Hmm, I'm still unable to decrypt it.

> the first public key shared is always either incorrect or the private key is lost

In this case, it was both. 😀

**Comment by JD557** [comment]
Can you try again? Sorry, I missed the last `=` in the shared key.

**Comment by carlosefr** [comment]
Hi @JD557 ,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to org@pixels.camp. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (carlosefr) on the Pixels Camp Slack.
