### ISSUE TITLE
@pedroleite is proud of PixelsCamp

### ISSUE THREAD

**Issue by pleite** [PixelsCamp/pixelscamp-forever#22]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt.

This is my public proof on social media:

https://twitter.com/pedroleite/status/1305486708927082496

### Encrypted Name and Shipping Address:

```
U2FsdGVkX18weAo5HbakUuR5iDJE/tgGFNDiam1nu81AHjok5nwQqKDDMUMH+EwLS03tXAs8IHeR
pioG1dpldyb25z/Es37KvjDCeQerOJcifyQw10kCQkyGZ8oSN9bBgHdtO13XhI39r2BFLiAVeQ==
```

### Encrypted Shared Key:

```
WplCpGzmGJXxu/Hu53lwoQMiKv2yjA8XplGaAWxqhUN596VEGbTAyB/BIBrPdQG9vjj/WVKMBko8
xCYY5azvXOFlmOElFYtJwpL7Nh4cUQU6jhxJ2h5YE8s13GY1aDrU8zvWenwQln2060aZUipCDz+2
TEp5khhsC1mZ7ywpNpGVY10d6KEKQ1oro0J05Rh1djask2Qui89AvtQwUPmIsj55kQ6k5sMVBmse
tScEFU94zI9aquO7BU9WPHdmXwJFQKiVaz/+dlJj/6A+xcqiaGzlVPuGsOIAh1GiK9pOrFR1Cqya
fkJbS2S2S0imUf9Qf1/GsgelJgje2aTkHiYe6UUfhI1fumSMwLAa4laFadAD9tOwRQuWvShoStX7
SbYi9afQTX+E7bolVu9uAp1RXdpU5Nl6NMAt25RvYC3D+GKTyzeY7lWWrWvz94c0Yybp+jWomPFG
yu082e8U2qq2pdrl4aZmrH6kqCL9J4xTgT6uugEPkaqbJckL3TygTlheg1BKTHS3eq0/JiEYKq92
uJfd7UEXYaAu4suVirCj+7eaFUJuRv5r39jwvI/s3YtUijLCkr7QNdIg5BWUQlWqOeXDlrZZbiT7
c82LnpK3Gxx+gdUpqtymP6JFEdA6WTL5VEDRDi6wGlMOk6qFvknxsCJNwvuceuma1yLzOsAD41k=
```

_You can edit the issue and paste the encrypted bits later if you wish. They're only needed after the request is accepted._

**Comment by pleite** [comment]
Size preference M or L

**Comment by carlosefr** [comment]
Hi @pleite ,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to org@pixels.camp. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (carlosefr) on the Pixels Camp Slack.
