### ISSUE TITLE
#pixelscamp #forever

### ISSUE THREAD

**Issue by beatriz** [PixelsCamp/pixelscamp-forever#23]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt in size L.

This is my public proof on social media:

https://twitter.com/bibasm/status/1305477818193674240

### Encrypted Name and Shipping Address:

```
U2FsdGVkX1/ED/qNUVc6kVRxK/Cyivi0iLq82WdAPJ8+wtuhJUkf8Bk2ak8WDSn7nAAtH85ixnhnRxCPf4OIuCmYU5u/8LFNDZ6UDrgZX8apSZvJ2PksJVsnjN/+mBez
```

### Encrypted Shared Key:

```
kh3beT8oiSlJrCwF8brlTxaIoO11vbyNHtGZbOrCl1GB3i4lpnk+UPsSBVpdKZiVCAtYYUNKyNOaURt8lTnnm7pb/ZShZiDJgPVvnE73wXVjgo8DMAgPJCSkBT7ei19AhcTQ405e6s8F6YeehaWArgKkAjIKN1h7PkrGAtfvUIQ7s4IvJjYrrjlmU+z1n2bTVKW9DL+ISpQk/TjDUtSSiad67OnSmdDebnf8uaomwJbYFhdnMaftjlW9BgTWV77cxf4oRgZTnqsHLxYV3wag6etEjb6UXFeFvnyfDZIOAdDMpmXSHyk+A5W+hV2AiqKhMwwbS3UX+qSfMS+71+gHETGGgfM46dRr1PPSJhCphdONoE/tpSvqOcl59gBIKJkEHxJtYedjJBLqCkqcBujMRbn7MjeJtmrw3llE2B9czAyG4jGTUyoJG4r8Oa0Ge91d3gN6I2VtOTD/9gqqN6pCxkXtTIb++eOJY+1PhECvWSZvobDRSKPnRhtKdSagCqPPIBTGeCtvDgdZjgIKToeMl2seFi69GGRf9l6xhIJxckEi30A2N71gOqq91g/UgGvj0pIGSkl6XcO5pAqzbdvJxuI1SF/TyoCDjrfclpQWHUyhmmz9BOopJlvvGgbIJ5Af2v8AY5ZGrOh6Sm079Sm+Ntt8+V0OWHsboj0NMdrXuqY=
```

**Comment by carlosefr** [comment]
Hi @beatriz 

Can you please regenerate both encrypted bits using the updated information in the README? The initial public key was wrong and has been replaced with the correct key, plus the OpenSSL commands were updated to ensure (some) compatibility between versions.

Sorry about the trouble.

**PS:** If you have a preference for t-shirt size, we'll try to honor it if we can.

**Comment by beatriz** [comment]
Hi @carlosefr!

I've updated the description with the newly generated encrypted bits and with the desired t-shirt size.

Thanks!

**Comment by carlosefr** [comment]
Hi @beatriz ,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to org@pixels.camp. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (carlosefr) on the Pixels Camp Slack.
