### ISSUE TITLE
@alcides photobombed by @celso

### ISSUE THREAD

**Issue by alcides** [PixelsCamp/pixelscamp-forever#24]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt.

This is my public proof on social media:

https://twitter.com/alcides/status/1305494646689280001

### Encrypted Name and Shipping Address:

```
U2FsdGVkX18UIuvd5cjTgItV5sp8Q1Rv27Dk0UByjfRs2sn1/IbeuFUuflA/Fd2aiiZh4XAozb9ltatnQdeudxaiu3uvvltlQiSxQJxDejAAHDvwlFE1PQ3E4kLSIiHDhqyqYI5Ok94E8fYU/YsTpA==
```

### Encrypted Shared Key:

```
M3BwHRwGdU0VoYHNWJV9vTz+Pd6nt6WkqvN6aoI/Uq52Eev02jC824/ryfB3DcieYbPjnZCnxPvYNUmKw6o8MoL/R9mks0xKwn+fdewKSF3XcH0R/F3EJF9LcRLKKFUT2xQhabr6pbcpGjkUD6MKDCuwpTQL17XspZER4O6rt0+Ut/uMj8M8Bd4YMo1uhYpft0d2B9qmj3yRONqALOe/E5DlQylYSfXe9hgeb1zHyMsz7zyJUxQH1JevbTNHTp9n0gvwHce5wT+iaywG9mZeap0EpYogJf3ZRCVVNYvUo1ub8x5THKsL/j4L8LfL511kcXURrpjFOf7uxt6VsOBHeS3BuN6zGLFW0uGAkSD7botK7GT0W6NWCetJGQyCqJgz/aqj5OMJgWD3uk/Ew+He8BljPx5jHj9sy1RPZ2HT6d7NPgq2LDmLhcXRvHLhTMgiOldxqtieP+vZnCa07dZ3RpHWyVwLHj1gSxNh24Dlf82dzRZESuJjJt/C0dlBU36cHNyESd6kV5PvdwHLy55Fcgzm98JComkKfcHoj7UqEW0N3KQQF3PNYawFk1YGoJDmVI0fLRPqXW8oAP3nSJNfqhADNkXq7e034YytElE9FHYMGbbTLoGVPEE0RQxdPIT2uZjijfDu16dRrljhOa1jLRW31gvlps5U8QgmZp1finI=
```

_You can edit the issue and paste the encrypted bits later if you wish. They're only needed after the request is accepted._

**Comment by carlosefr** [comment]
If you have a preference for t-shirt size, we'll try to honor it if we can.

**Comment by alcides** [comment]
L or XL, please!

**Comment by carlosefr** [comment]
Hi @alcides ,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to org@pixels.camp. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (carlosefr) on the Pixels Camp Slack.
