### ISSUE TITLE
Pixels Camp Forever :) Miss you. #pixelscamp #forever

### ISSUE THREAD

**Issue by vibern0** [PixelsCamp/pixelscamp-forever#25]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt.

This is my public proof on social media:

https://twitter.com/obernardovieira/status/1305499758178512902
(Me and my GF. My badge is under the shirt, so only a bit is seen on my neck, but she has her visible)

### Encrypted Name and Shipping Address:

```
U2FsdGVkX1/i43sUoU9ALpLlRcLbRF+J1mAZDC+0vrFVYSDEpSuHnd4ctp7XJ0BMlfnLxVuZotXJ
b5ZBWOWrQnVv4HIqQnEKisCISn01mzkpw8zMCqs0cCtKNZk9JMcYWZ+bTIBx9TXnLiOapO8FG1qc
bAxreAPn/zJul7Djmu7F/wsHoeIRrXFlKvG5WLYFu/f0DNb2SP0LgB0s5fVdM+pcTUIZI1GyQStk
jrg5kKdhFVbeDC4AhVxGafMBM6/IMX7VHWGS17QFJ5K/oGkcYFUQNahWMnUTsGdHTvl6E9qjv/55
fLU/NXaxUYNbXdTtSIZsY1Whd/SNeSCHYiVY9r4BObOscnau3iBrSz2uT9bt5BDrWLFbWyJGajBU
XAKq
```

### Encrypted Shared Key:

```
Yqq8Sgyjpu0lYSz1+2X6LUrk3ykjUXZNTFauw8YB8xtPBUIGh6iUuBDtKbfbY9/r5mX1F8+lWe4z
owK/Gi8Iy/mOiqA7AfoOrbLki9/Uk0WEK28ygSzw77Cm1d5FPvXQ2yot4zeQIG2owuFaVaO4fr25
ArK5VgNEHsp8lhZtaBDiuzWT8Pa/jhoYNwmeN6fxy3s5pOXkVUl2Wf4JADRl0AViphT5ixMsa7Zd
HlOQQXuMLR3wEkIXR8/HaQo26cGBOnoOWcflbc5UIlM5QZOZIosRN/l03vo1+3GvNZDHuh/k2j5b
GIeuOjJ/1+BA/Hj7a0kvQIxQ7IPSBW8MfWVItUdf7CRsFUA0P2/67VPUfQ31CFmvZye20oek9PnP
aYTWKS0sk2HoQG0ywRelNuOK1Mde02xPbch5QOjjftT7x+cB/MFiXObzHePYW+xJktxDyVr2VaYt
XoVQfVW6XuytM1hS7C0CCFzmTIpZU2lfXQhYYmWjL252GmE91OpX2DYCF3dTQ70RKrvpKTOvI/NE
ZICursvwyN+Xf6zbY+74TzgaBtOGlB4E2+FDLs9NoEIxmTCKmuVEVEXOUxrtvmZqyMk7hso6i0CS
yMYvkgQ1Vv405FViv6U/8lZU4qELg7YoJtIxQ+L5APZ7cFrOVYNwbmRHZ4hQuHkMzFuFCUAqRsU=
```

_You can edit the issue and paste the encrypted bits later if you wish. They're only needed after the request is accepted._

**Comment by carlosefr** [comment]
Hi @obernardovieira 

Can you please regenerate both encrypted bits using the updated information in the README? The initial public key was wrong and has been replaced with the correct key, plus the OpenSSL commands were updated to ensure (some) compatibility between versions.

Sorry about the trouble.

**PS:** If you have a preference for t-shirt size, we'll try to honor it if we can.

**Comment by vibern0** [comment]
Done.

I hope I did it right. Thank you.

Hint: Next time guys, consider https://www.nucypher.com/dynamic-access-control 👌

**Comment by carlosefr** [comment]
The answer to your question is "yes, you can". 🙂 Also, you sure the lack of postal code won't be a problem?

I haven't heard about NuCypher but, at first glance, the problem with it is that it isn't obvious what it does and how it does it. In fact, I had to google it to have an idea of what it _is_, because from their website I really couldn't tell.

Most campers should already have a rough idea of how RSA and AES works, and have heard about OpenSSL for sure, so it's easier to audit the process and trust that it's safe.

**Comment by vibern0** [comment]
Ohh, awesome. I see it went well :man_dancing: 
Damn, I'm not used to writing my address :joy: just the ethereum address :joy: I updated with the postal code, thanks.

Regarding NuCypher, you are right, it's not obvious. But they are at the very beginning. They don't even have a stable product yet. I've had the chance to met them in Berlin last year. Great team, doing some kind of black magic. Mainly [proxy-re-encryption](https://www.nucypher.com/proxy-re-encryption) and [FHE](https://www.sciencedirect.com/topics/computer-science/fully-homomorphic-encryption) (fully homomorphic encryption) (also [this](https://blog.nucypher.com/an-engineers-guide-to-fully-homomorphic-encryption/)). Not a new topic but not much explored yet. This with [openminded](https://www.openmined.org/) (federated learning) is mind-blowing for me.

But I know nothing about security :joy: just sharing these amazing projects I truly believe in.

**Comment by carlosefr** [comment]
Hi @obernardovieira ,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to org@pixels.camp. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (carlosefr) on the Pixels Camp Slack.

**Comment by vibern0** [comment]
https://twitter.com/obernardovieira/status/1341851386745647112
Indeed arrived. My bad.
