### ISSUE TITLE
Pixels Camp Forever!

### ISSUE THREAD

**Issue by joaopr** [PixelsCamp/pixelscamp-forever#26]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt.

This is my public proof on social media:

https://twitter.com/jprod/status/1305496915992342533?s=20

### Encrypted Name and Shipping Address:

```
U2FsdGVkX1/60DIxii61LWWTRylmsye1J9XLK/diQTpo6zUmZNyRIhsWDVeItoCcjWYSfm8m6+CBQyhKZmNZfrnZUfLwV+JsyWFmeqzRNB+ob7EUV2wdsmIwYesIHG8Mei2dVR1vRlCnXXY1lx2LXQ==
```

### Encrypted Shared Key:

```
jdUwLrTsO6UpIkTGIh6kezQi8B5LhUYnunlA6G2I8b3S4o+WEbmlNbozCpV1X1CGGb5Mryzfse1E+tfBiXgjNBJTy1dLkMjtRwgvt1r2abDWJit7ydZmsLojdNzIGcffLwfb2HyDa8AOI9AoPLvMkKv+3B+CfvHUzj/oaZ+KGf3yPuKQTeh0SMDTySoF1lQgrlyfxGU2cjMhPcVCHG4KdIMm9BRA3iWFR6KgoZ4UYhR/98SVNj2QcJo2vO2aZTFzExMKXHc6Yy4EL1ErjbGSDBlOMlo8J5NGSghEb3Nd+TlONIkqCCA9pAu1c0UpAkgJ3mPWQ5zgzZpjphYdipAtNty9JGubXPGWB3k6T0QB+TUYEZq0qGnzzXgMrtZoPGwp0E3njll1SEXXHJTje2cbvQaNxRdIm2t9HQylL/xNLtoZDGsJbGWrhS/VQbLQAzg+DGEhhXclFs1SzVr9dxBvmgQU0TCc/B5q5o9bNQT6+lIKst2fdC2zohmh+ug927BcToE1sBIImqhytnrCh1sch0vbXuJnF7JcvXpjnSoWRiA07W3o4fBxjtgcPcnZrpV3kxc8KZHHWe96b+ssBB92mItoyT0/cEISCy4LwD4ApqQqzjQFnAiFD6xWNZg3iwvTfmrQCVbU/AoySJ/iM1vRngaRnYfNnpmzEczmVsga2L4=
```

_You can edit the issue and paste the encrypted bits later if you wish. They're only needed after the request is accepted._

**Comment by carlosefr** [comment]
If you have a preference for t-shirt size, we'll try to honor it if we can.

**Comment by joaopr** [comment]
If you could go ahead and get me an XL-sized one, that would be great. OK? Thanks!

**Comment by carlosefr** [comment]
Just make sure you fill those TPS reports.

**Comment by carlosefr** [comment]
Hi @joaopr ,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to org@pixels.camp. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (carlosefr) on the Pixels Camp Slack.
