### ISSUE TITLE
Pixels Camp Forever!

### ISSUE THREAD

**Issue by afonsus1997** [PixelsCamp/pixelscamp-forever#28]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt.

This is my public proof on social media:
[Here!](https://twitter.com/Af0nsus/status/1305512418144063490)

### Encrypted Name and Shipping Address:

```
U2FsdGVkX18fxdIAJIabYv86l0DvYi6XoyGo9V6J+0z4h1OjEdTwKZpblc9fb8f48hRNbm/oWxia
BVIy2Z/AL0RrQiyBkG990EQ5tCvmEhc=
```

### Encrypted Shared Key:

```
bFiLmk4A8TXBuXBZgxm4VG28kI8gDCa8z3SeRF65CEHdQ9cg8tfltPsz/KMlMpdE7TZSQKBZSiJE
5dH9I4HtgDC0fMqYHz7q12Opu7NcLHPGLk51bf0DfccklBJTEglnQUcIC/64po+pXxwXRpg6E5H4
D6Vs1Upy8z9+kBAJo1tOnmx8mYrnSUnQ7+MwFTHcbQ/bET1Xv4rCp77sCx76ArrwwI/mZx4rBghm
GHYyRslFjociTr/pXu42sMTAWYSie0w4WkUmSJ/TXW9nQyNP/st0tftv95Xw3wiuCPlPReXLlION
PqEnmWzHT9rvT/rcA7MVsaUTR1MHHREVqsDaYD4K+8NAr4wMF7eFfIMwmlC3H5hwl4GhgZx4n/9U
1ex0tGDbytGZcddBQ5nAtkiiapOqsy6mpudqOVy4N+PUU+IltoT7dRgjSWeG/brMXZpUT0jMT3Xz
PfitBxKcvJMxzvelQ5/T/pKN7v9hNWlVILtNrf66UsaJpTZEgaAixPqWhz2C5B8A++R0hFL8x//Z
Lv3+B7x7gq7Gu1mJ3Xks0pNNCBb7pLncmg75dvoNnBBBRbqFbh4eJf2A4ufjOJCukMaqmya3lvmt
YawMR5DG19QKubqYoOYtFeu7IIY0OSWUDj/LUb+MfofKdCOq9Ru5hEqgf7zqiK0aOOQv38gCjig=

```

_You can edit the issue and paste the encrypted bits later if you wish. They're only needed after the request is accepted._

**Comment by carlosefr** [comment]
If you have a preference for t-shirt size, we'll try to honor it if we can.

**Comment by afonsus1997** [comment]
Would prefer M, if not S.

**Comment by carlosefr** [comment]
Hi @afonsus1997 ,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to org@pixels.camp. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (carlosefr) on the Pixels Camp Slack.
