### ISSUE TITLE
Pixels Camp Forever

### ISSUE THREAD

**Issue by antonioalmeida** [PixelsCamp/pixelscamp-forever#29]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt.

This is my public proof on social media:

https://twitter.com/tonydapinta/status/1305516014575202305

### Encrypted Name and Shipping Address:

```
U2FsdGVkX1+da/3K1+BzwVXQU8y1XsM53I0thzYsaPGsHsDj57B3jcB+QHBNu1WIdGvhQgq/MnoCy+X2FXVSqk3rUFEJGAFvIi8l4bx9m8E=
```

### Encrypted Shared Key:

```
dK244RjsIDyGl5n5c8IhshFrpyN3kxAgKDs5sys7CHr70cWZdVextKtlpmLVmXekwPrbUaDYRjaX
a3YYkC8DHY+DnrnCxzU0oE2W61SxeBtxIIo+K1w9OVWyEnrOJ7Co9EV1NzJepLvxvyi2iz1iZoc0
btqYmjtzQrom+W8FH5gPPhk6czK75vo7SMGePMaIzODNrkVRE/LqRv6CaNmlq4MMhDV2CK5K761v
l7PrU2M5XVDDvjqS2ETtNUG2ZGhBs6W4prIo8Dsl+Kpsa4X0yvnMO/cG4NBYSU8jIg8/wTuFsh+V
djBMYI/2Y16URTkom+Ma6jm01BFaoOjnqfovCqlmM2MAFW6EkHKdv09M/O4FxUAUEQvJ3rfH1Ufc
Yv3W6tBE/OfmLapAmBL5LuxitDVPjqzSVxxPJ34QFV9s84+rnwvI07BuN+pJVd1MqZrjo/JSrGwx
HqOVaQ9aX/p4lV1gqpo0ZL0Y9/ZVYSYis1W1GS54+aAifhW0PPiuNZXOqqEX5trzvXE+9HDYy3vB
QwpRoGJ23Hm7D3C/xcOpfEoyLgXyex9NNSY8JeSCkIZHWgPi5CnejjUphOkrWzljEXNiB/sLX29R
Fn29V9cZfb8kw2ALS7qH/rAZ6NoHsSX6FZUT6hcLFmXGL1P6NKEgBAqXn4mxR0Ao6S58lp3j2bM=
```

**Comment by carlosefr** [comment]
If you have a preference for t-shirt size, we'll try to honor it if we can.

**Comment by antonioalmeida** [comment]
I'd prefer an L. Thanks!

**Comment by carlosefr** [comment]
Hi @antonioalmeida ,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to org@pixels.camp. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (carlosefr) on the Pixels Camp Slack.
