### ISSUE TITLE
#pixelscamp #forever 

### ISSUE THREAD

**Issue by gadelhas** [PixelsCamp/pixelscamp-forever#3]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt.

This is my public proof on social media:

_https://twitter.com/nightscrolls/status/1305454650439725056_

### Encrypted Name and Shipping Address:

```
U2FsdGVkX18spXgON7HVsBrwpOHSIaQ+t+Xr3i0bJ2DIoKyEQTPVYceXK4Impsba3oPyvLta31Mr
D9eYrlDNNb3rDbYNpgb4PCwKUN+8q8h3XWzFQZv8bIOA/4BNDfpD
```

### Encrypted Shared Key:

```
L+IYXymOA1d47gkf3j4xqR10lGCr/Yxpmr+lcji7/o1JkbTE7v7OqnQpA9HWhjHFiTm3UAJVkNlB
SWhIdOe+NYxjM3KK+/oDtPIj8x2ORZCMIazIHjwHUlCK97qey3uXbu52qgiRDCeRE0vQVV2wonR1
94EdJwnSbUsUI2Pshcg0zUpIGQaDNJHsCbMi2VIX6FryeGV6c4lwTQjzt19+V4sishJFMHkFVeOV
7VjRXuYBQI94QRzTgAmVhXNxekcE3xZNP/ZGJgck2S5NFCYiszhz4H0LALlm5/VPII9W+0jqdGuV
E6g1ylW6uFsyFyenGATVwT6EgHNY7yLDQS2eqlY2K3wnTz5BxDQ71HLb/CiUj+HQYBZYrwpgmx4g
6fIQu5ikPFeiFFRX4VDP9pmSWu+aVuKSCJgpJ/dQJHS4y92gklD7u+eAy/1s9+ObspY/ZIBhXMOh
i0vIp6RMzV9772i97J8aGtCZC/+5Hdlc2Oon2wVHIh8LMGaag0eb8ktH9GxGpWm96Et2pBW00L1q
pK4Mf8ZzSMNTCuLX/J2Q26R36iQKSnkjxnCZ6Gr3RcxVIOzRPGBVVLEAGLRaMhVXBV4jWoy/fOgo
2cTZ2O2vTl9z/NqWuBpVWn3wXwc62af+Po/NnEe3aTKTUawT+eq4lR5lC+0PoVyZArZ/PBX8lW4=
```

_You can edit the issue and paste the encrypted bits later if you wish. They're only needed after the request is accepted._

**Comment by carlosefr** [comment]
Hi @gadelhas 

Can you please regenerate both encrypted bits using the updated information in the README? The initial public key was wrong and has been replaced with the correct key, plus the OpenSSL commands were updated to ensure (some) compatibility between versions.

Sorry about the trouble.

**PS:** If you have a preference for t-shirt size, we'll try to honor it if we can.

**Comment by gadelhas** [comment]
Hey, I have edited the keys to reflect the new key!

My preference would be a XL t-shirt.

Thanks!

**Comment by carlosefr** [comment]
Hi @gadelhas,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to org@pixels.camp. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (carlosefr) on the Pixels Camp Slack.
