### ISSUE TITLE
Pixels Camp 4evah

### ISSUE THREAD

**Issue by msramalho** [PixelsCamp/pixelscamp-forever#30]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt.

This is my public proof on social media:

https://www.instagram.com/p/CFHyaiagG3_/?igshid=1nv7cwftbmxsl

### Encrypted Name and Shipping Address:

```
U2FsdGVkX19x+O+faU8GTgqEWKEUrvexxOC96ZTW2Zlh15xSjDLDH1/BmEBAWzQtYdTRZjrVFOucZdWgjyNHrrfbupuHCv7qExzSJcb71tBWhuH/S8DeG4F5wVF5OhiBhWBskiSAG+JKde4jnUAZ0Q==
```

### Encrypted Shared Key:

```
KZnJJoWJtJVIKbtwEYDLFLbE8cYKOQYG0m6GAm1uwq4mAnjWtrDrRXYNz5qtLRo4Qki0y9dKGEPL49maxnn/j21jWM7uoRQ9ASk5z5G5TwKQ/TBPqGYEaufyPXuOxRCARaPXQ9xmgd6wtfuWtzqWaa2zsWGATkbhpxv5ZbXRplCO3990TE7+Lek/Bq104lUQvBMs8EDRkKioSqg4hkSkPTVHdAxBTvmhn+1VWo1Z5B7+9zHiVNseX80CkTagn/41FdWZ3WwsHDi21++27lf7J/1nBvA7F/N8HIHFDY7R8ayPoZEBNcvdFhglVqzRwIBuFQ5PErbDo0SroOUSIY9XocEPZRb7iMq1M9do48dbEzt2NBHk+IG4xBkw7hGmn14T9HDEnORnyqiYHKivZgDVM/5ER+BAlsEaLl5doCPPTVZ9BZb3diJfKJWyBKSt48GBWmf6w0LpEC4GsAUmRCRA+WbgYbiIWTK+t0tKWb6x09OnW2znSOwIZRB3+fhDUujjL2bZpBvO+hElYfkkNnxQ/+AyIwl/Yqi38oD0lAoYAHqV+pldRsONiM5lmUiTdPObvjNJ1VLAnJQn6BA8fjBDaLfhdEQgGBcMO+FjUoa6kUMnJGUHtZVnwg5ly9FvW5NrnfBdZzj6z4X6777nErj9xkv829/cAhBQhun+Yqzo3g4=
```

**Comment by carlosefr** [comment]
If you have a preference for t-shirt size, we'll try to honor it if we can.

**Comment by msramalho** [comment]
Choosing not to encrypt this one: L.

**Comment by carlosefr** [comment]
Hi @msramalho ,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to org@pixels.camp. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (carlosefr) on the Pixels Camp Slack.
