### ISSUE TITLE
#oneofus

### ISSUE THREAD

**Issue by killmaster** [PixelsCamp/pixelscamp-forever#31]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt in size XL or L.

This is my public proof on social media:

[One twitter link](https://twitter.com/kill_master/status/1305612716774699013)
Pretty much every link [here](https://killmaster.netlify.app/).
Proud owner of the #oneofus badge.
Writing a little article with @reaperfromhell about our journey from the old Codebits untill the most recent Pixels Camp, documenting our journey through the events.
Will add a bunch of twitter links in the near future too!

### Encrypted Name and Shipping Address:

```
U2FsdGVkX19s225Rkpf4WnsDugR0AfUt/oOYIFrej27SEzOO9NFz1OceMt/lxjrrN2+iKLR/zsCr
DF0SoiVvcqCRR9iRuVybpZ4EPybNGTZD7CYbVGpQIfRhznbgZ/Ff

```

### Encrypted Shared Key:

```
EfbD8vAMDRpRrDNdwBT2LqlNfSRR54UWPGNkZhWMg57/LAf2EtU3nEw9dy15qRWxFm/Zb5rHit/+
x1ED9QH12TFhA9yxN13FYdABuGOpD8ilsc6WUg4WYH5onWsdkNULmbLQijCkbTf+OFurNxDMm9Ik
aPDhFkiAJmSFtvbQFuSFOJjqqq3tMNyYaMUvBFl7tX1nkikhkKIC9P8GQ9Pr3xn3b+VsGddT/cHI
LAzxkwFOfpJwXQ9nhlaAnwCQBqrCiAfVTE+rY0Tn0fwB0oASaJL2fQ78RzhTA/ZspHfMuDzF90We
5cpZbCOtaVfc/q8trLlc/SeIGxiA5R1VSOqWBoVsL3659tsu2j2y657dgp6yl23KhxBdEo7iVH9t
aXXXDbEOgJC9MUV91JcqailvcLsf4MCgm2Snfj8w+AtAoG2qjIwjPjyWjMHP6Yw5a0IX7jo7AFqP
RDh3DDaSeuebuugn9f7/UsA669aRfMU35/xGT75vUwJArvGo8Sth/QYTtivLwe3lrx3HEcqHu09P
daw2KvbwpQAYjT467ILxAM/WRfSCSZ37hLVFwlrkFVM/NWkj4gt+cEIU1BJfhmL7OjzybNi7tNE6
Ds2tdK5Qyc/7BRVXTOQ+hE6D4cD42I8dhJHAaxIpK20SKjiCgdZIiiaDAnGtYAIQpRB3FqXmFe8=

```

_You can edit the issue and paste the encrypted bits later if you wish. They're only needed after the request is accepted._

**Comment by carlosefr** [comment]
Hi @killmaster ,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to org@pixels.camp. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (carlosefr) on the Pixels Camp Slack.
