### ISSUE TITLE
The code of conduct Nostalgia.

### ISSUE THREAD

**Issue by adaptive** [PixelsCamp/pixelscamp-forever#32]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt.

This is my public proof on social media:

https://twitter.com/adaptive/status/1305525036888076290

### Encrypted Name and Shipping Address:

```
U2FsdGVkX1/VTuJjgiQ6mNs6hyzXDvx2mfj+5XjoolYu7Qlz+Asv7TjpMkow6Y+SwduB41CvgxSc
gT26T7pPXcOO2Pv9BTcU8xP+cZNDHbw=
```

### Encrypted Shared Key:

```
gATYvBry5tPDgojU6wX3pot8XvJQvDWOxJgMYaNcLUIofm4arFRLaGq+3iNb7HYZaRUwWbv/dYcz
pedwmgzg1DOdZNLDYHexD9zuRFANp+iyY2WwrbQcm8ZCJrpsbe+exPWhIR/OZVvb4BI287SFN/td
uIA+Lzk1+XPxLn+EdLSzNswHpWTKLq3NvoLr1K0nfGC8nTKCn8maoUZ/TdkApcTO46f9oGzTcK4x
JW0OQTZgG8jvqTJK0tV6iXRGUrIRGOJsCbHYCW+YghHhzxF7ZoxBq+9qtoWEho4jDjkO4ZGlI4G9
rnyNH371UKKd+1HEN6/SiajZWV4IeqWcS2MXl3ZYLQEx50OQaif39WEm59OQ2A7AczqUQLTegPWI
ud97HFMMYyGnB5DAMzG2imW28zWYhg3CZJc7oPR9fTGDVY7Vy0R6YYbBgBaKp1ctfSlrd3Fpoa2i
PFgxtYNh/G+QYo+f0shhqo68HVLKcUaCzn+ZTRGM21PWcXgpqqjEITL3Vb0vC2rBtUlwr6zWHRq7
j1CRGrjL1as78wctqarVh3762ftTJlgMuLRe94twLQXPa9tAlKS6DDQD28xs8TmpQfVloZLtRNFg
T26jGr/kqIXaP/trppSJM/9R8AZ/eFhvVyzIMV66cPps3KexgGU3+5KlM5TeFY1EkMxhXcX9l3w=
```

**Comment by carlosefr** [comment]
If you have a preference for t-shirt size, we'll try to honor it if we can.

**Comment by adaptive** [comment]
👏 **M** plz 👏

**Comment by carlosefr** [comment]
Hi @adaptive ,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to org@pixels.camp. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (carlosefr) on the Pixels Camp Slack.
