### ISSUE TITLE
First-Time #OneOfUs <3 

### ISSUE THREAD

**Issue by itskikat** [PixelsCamp/pixelscamp-forever#33]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt.

This is my public proof on social media:

https://twitter.com/itskika_t/status/1305529612189958145

### Encrypted Name and Shipping Address:

```
U2FsdGVkX18jO3lP9M6Kr1pov1lj7QDIvZBLpIb1YHxq1QNo38FlSthwA4W7IYpyuryiB4gYL3RP
q0AurMhRK+HeJ9jpOdwOuLi0csuE689WJi+bCfNam1JtUD30vn3j
```

### Encrypted Shared Key:

```
dHE7Nbxz9azQJ0unU9M7VRv/gLi2DONtDKu7QKeN13NIz0xGEIbS6XXIC5ECceilnQM1bEMZwytX
H+DkCvbHfUhMXJXoNhhMSE168PEysPiQ042RroH9E5CxVG6UbyhnSnwZkb25OSVkVNMNdQx4nEq5
Rtu+yT3dpe+T+O8klQ2sZkLrRJVUn885VfNsXNw7/SEyCzJQr/Y5Qb0c68U6MhcSY2GL0mLdWbNx
f4pm50Mcn4hHxr6t7fF0kRpj3dhSvvGsKYdhHPaBNCCUXrFKLoUa8YsT7bxwcvqMirN2gKghun8X
NuJfUJ+AvpwiET9COSu9mosmdAG13gPxIAQkTJKf/lHUoo7srXxG/0Vebfbb4YjWqEnqusUfPvRn
FrO/7+OtI04djEGdIefUEyjemfazGSgvi7QzL2tOsBUbaXjXalU2B/B2WFeGb6dtaGc6h1lcrH8C
Hlkb0ax6GOEa7ZEHEsN3HwjPF42O6Wny4VwhfI3gD6Wx3Ft5Lm2+nvAZfB15haLSmg5FWIIg+B6r
cXG14mcH3Y+Kq206U4VQvw/L8rf8IIaeODDYwIeWO7Z0pp5bjJ0v2M1/DPaIqNWG6OucfD8VSqZQ
c4AeEugqP+h0lKSMmzWiAK8GEzQMskPLlqWxfUIOeIqwGuqa3v3Bd89QNyVduBKuyozPn6mzTdw=
```

_You can edit the issue and paste the encrypted bits later if you wish. They're only needed after the request is accepted._

**Comment by carlosefr** [comment]
If you have a preference for t-shirt size, we'll try to honor it if we can.

**Comment by itskikat** [comment]
Hey @carlosefr ! 
Size _S_ if possible. If not, size _M_ ☺️

**Comment by carlosefr** [comment]
Hi @itskikat ,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to org@pixels.camp. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (carlosefr) on the Pixels Camp Slack.
