### ISSUE TITLE
Pixel's Swag is the best Swag

### ISSUE THREAD

**Issue by afonsojramos** [PixelsCamp/pixelscamp-forever#34]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt.

This is my public proof on social media:

![image](https://user-images.githubusercontent.com/19473034/93109642-390a3700-f6ac-11ea-90db-083b1fa20fc1.png)

### Encrypted Name and Shipping Address:

```
U2FsdGVkX1+U/FUCSQ5T/wd1L9lRGYhY09qLl3PnrchQrFkxLSe23DUZGAQq6vpdYeAP4mLu0+Ui
bG+bHprUrXOaBvGD80wJSPq8u032if7f8MSGX1i/p0TFoAe+Usip
```

### Encrypted Shared Key:

```
Z6HRsO2BG+egXQ1/4Kk+BCzT0bTzx8nB8/NPmjEGvqZme2KTpTy6WQ3KqVoXs44YkO2kBQfoxUTL
T0tbKLDSuVcAA+SNMbChpJtU5+fShRS1gVrEN/eENlbwIIVk21nJpdOjqmWFCWWNf/Zk1cWBiWj6
vAuATYta7fxn6xjlkQdEZTUrp0rquB9bEQhR3LVS1VBqQ/rrA+uCzlmEIVIIIlg8MvwsFxZnZdpg
/s91klj7b/XeOFlqhbz6lSO5UHTa83gxmr/iSH43UVsLsQ07XfhL8BKgnKzaX8JU4bzx+hqTGgWm
P75Yj/GE/R7HA/ee6JRvsQAvNeY2KX7dcFjwPiX7+KtWAfaBiHal6g6oftubLaovWwvav8cX5MYw
Xw3PcjZF5EvvXrq2hgCdVhUW0AISv6UpGMk2e1u1+TVoAzVGkyGCse9shIZBzfzP0jZI8oqrcLxj
cDYNVKJdQkRW1Jq3ZoXYFAAigu976h2G/Yxvo3UJy6mL0l2vLysDDgTIQBPTln4bFXr06PGoDJ1N
FvYkkxZcTlmX+Jcek1PWFx/BXNdb1oCFEqc5kB4jVlKfNy8WI2BVS4NQicpJhBNF0VNuI1ha69N6
IrbVnavSMEKtwTHH5jET5/H4OjJcFR8h9+6Qq2eBQqax8W2c3Fv/CHy/E5hT2+uup6E3QjudiM0=
```

**Comment by carlosefr** [comment]
If you have a preference for t-shirt size, we'll try to honor it if we can.

**Comment by afonsojramos** [comment]
@carlosefr An L if possible 😁

Thank you so much!

**Comment by carlosefr** [comment]
Hi @afonsojramos ,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to org@pixels.camp. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (carlosefr) on the Pixels Camp Slack.
