### ISSUE TITLE
Pixels Camp Forever! t-shirt

### ISSUE THREAD

**Issue by edgardurao** [PixelsCamp/pixelscamp-forever#36]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt.

This is my public proof on social media:

https://twitter.com/edgardurao/status/1305542975007621123

### Encrypted Name and Shipping Address:

```
<<removed>>
```

### Encrypted Shared Key:

```
<<removed>>
```

_You can edit the issue and paste the encrypted bits later if you wish. They're only needed after the request is accepted._

**Comment by carlosefr** [comment]
If you have a preference for t-shirt size, we'll try to honor it if we can.

**Comment by edgardurao** [comment]
Hi @carlosefr ! Shirt size XL if possible - many thanks!

**Comment by carlosefr** [comment]
Hi @edgardurao ,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to org@pixels.camp. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (carlosefr) on the Pixels Camp Slack.
