### ISSUE TITLE
Pixels Camp Forever !

### ISSUE THREAD

**Issue by brunoamaral** [PixelsCamp/pixelscamp-forever#37]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt.

This is my public proof on social media:

https://twitter.com/brunoamaral/status/1305562525359116288

### Encrypted Name and Shipping Address:

`U2FsdGVkX1+drrvLgfGo60RAGfn7D2BmjerjogPXyl2XLcSl3vSGVDrxk20VrQLHQOLZVbZUPZ0FApKvStEtZjAu6uYIcK29sy+WFuHmT2s=`

### Encrypted Shared Key:

```
Not5jl4wn9CNX3dQjrKmgfnZPlLK7OhcMRlQQgy/90C2SUcvMOgaYYa1euugUtkd+yqac8dqXZUS6GBMrteub7MdzrG9HSFRPttw4yFP8EaENL4EjE9TIlYNEXR0wylG8ebrZteR8QRiaZSXaTnmzyCVTHisGCwhSBR1VM6fF3wV7Az/71pb8vVul8sl52fDAjLyPt3TuQc4btHnAqC0K9VyXjw3RIz8CJBxy7K+B/wp8owDNlAITJk07ZArMWcRvUzQH2YUhc3PfqgkLtUI9WorztiufOPtUO7jM/cQud/maQR4h9s3PYnmVsHTGOmIXrRC904wXKIevJFvnAExMk3pGI1Hwj62AtN6bGVbd3W3+g6m2UYDww9oiPoUHNlhJnM4FMb3xVNDFRZF6aqWwVtHYvc/vqLxJd6/VGxIVfekOL9ATcwkLbYK0BdgTFloPVXrLI6Qf6eixeXKMgU73vJHG3q0om5KTljCH9JuEgaGKIkXYsFhIpeFwr0kF7jqmLwvFkiU/diC9lL4mpil9IM3izF54iPAkyeaH/N0HZ0kQlfrFQnSiHKAxyRTJ94kJrNhM7y21IQcBlOWUMIP1ukCD8UsYhnwdUq4tKBfcOYh9dwsu36UgbJ/okPJPxWufcfc0zqnBZuH6Kb9+al0MI3kPq/DZIhwVMniA3ah9pE=
```

**Comment by carlosefr** [comment]
If you have a preference for t-shirt size, we'll try to honor it if we can.

**Comment by brunoamaral** [comment]
@carlosefr M if possible 🙂

**Comment by carlosefr** [comment]
Hi @brunoamaral ,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to org@pixels.camp. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (carlosefr) on the Pixels Camp Slack.

**Comment by brunoamaral** [comment]
it did arrive,thank you!😁
