### ISSUE TITLE
That moment when I got @celso on stage playing DigDug

### ISSUE THREAD

**Issue by rcarmo** [PixelsCamp/pixelscamp-forever#38]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt.

This is my public proof on social media:

https://twitter.com/rcarmo/status/1305566931165085697 <- a memento of my having organised the "Chasing Ghosts" event and shamed @celso into competing onstage.

I miss you guys, you're my extended family: https://taoofmac.com/space/links/2020/09/14/1200

### Encrypted Name and Shipping Address:

```
U2FsdGVkX18AlwZe4D74EAdTusCfB3nyYTE5tPNAbzbBZsWuSVvBEJ6sQX2ioma4j6Xlv/MqqztC
tfgYbwLrkhhIpQKqNGYWJQhCULnsoYA7+NWIsOywdv3LSaoTTgtX
```

### Encrypted Shared Key:

```
A+kC11leXmABGylmxs2/MEVGiJAZcSt236UncYY/L8t2uMM9dZLAc14NPreIxyglMPlSqrDA9NsR
rgB9kXON82xqlhKw8azRGAwuSH/dYq7uG3R/vv6jcDZnx92bgoAulRIjwdYMEtJ7/1JiRrE5mR4j
dpbTW0Be5z3z7BZwKQtF1kGlZveMRSojM+IoQZxxjCU90coOPyPe+uEQOR92GSxBGSqCa5RojXxn
mFhWL1TysTm19Qxqc1VbE59y2chYJwgs7wvbw42Qk8JG19qV1oQwa02/56xdo5HZxtEH4RQ0sDXi
ZUMQatt+jd5Mlt3r4s2p1khzCxScnNOmzE783+SdOs9wokDbRESJDs5e1aFW9GtkHI4mE7HFb/L3
OK/qcFOxORoa6DWUD20PaiEi6WDt156rZ35NXlLp81vWXNliPE4T1yCXGkSfNf06nkGzL5VtletG
lI6I/S7WfC9CcXlTL/hqFY79ofgncDRpELx7BqaWo8MQTaPK+pp8VkLp5aN09mnWeJA3wWq9b5dE
J0fz7gOGPd4A9bM7I/xrdqaDg0XgSXYqjT3zKJdkT87kroSEcI6ZUmt/0ZLu5LVHfVxzq5+s86fm
DNyQBgJsSsj5RyMqHYbIRVxejEs5CJ31N+fpDeqWIL2dQQfs9eFjrpwKSfJnI9sIiaGnlWOv4nI=
```

_You can edit the issue and paste the encrypted bits later if you wish. They're only needed after the request is accepted._

**Comment by carlosefr** [comment]
If you have a preference for t-shirt size, we'll try to honor it if we can.

**Comment by rcarmo** [comment]
XL lasts me longer (and it's not on account of broad shoulders...), but L may do.

**Comment by carlosefr** [comment]
Hi @rcarmo ,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to org@pixels.camp. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (carlosefr) on the Pixels Camp Slack.

**Comment by rcarmo** [comment]
Thanks, just sent it by DM
