### ISSUE TITLE
The lobsters gathered knifes and assorted cooking appliances and there was much rejoice!

### ISSUE THREAD

**Issue by nosuchuser** [PixelsCamp/pixelscamp-forever#39]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt.

This is my public proof on social media:

https://twitter.com/nosuchuser/status/1305572054595522560 <- part of the #lobsters team after cooking nuclear tacos in the 2019 edition. I couldn't tag them all, some more folks that helped out were on to something else, but you get the idea. We are huge fans. These were the cooks you were looking for.

![image](https://user-images.githubusercontent.com/1007018/93124266-42ea6500-f6c1-11ea-801b-a6c9a4ce4e11.png)

### Encrypted Name and Shipping Address:

```
U2FsdGVkX19KL6TVpgQOz91t2iC3JUUJL51gxvhojUwWbgg31kQvAJCBRkmtJIRrKO2X/TqMkmwZ
Xd3igHLiYUKGK6qqCS3utxKzzygIdDDljCaXNe/5CbcuI4tsTamT+xDGFzFM3Iw84133YYvW3w==
```

### Encrypted Shared Key:

```
VQ+HkuAcKoekG3UflgmbLA6JWZGLNEZ1J87oxSUGu+T/4hz2OiD9tTpjJN4NML+UClPSnVbJv4/r
yqJiS/aZ8YYImmRB5W8qSjxG8amJzmVuS9zx6DQQdgWJzu/QUlWunyWKBMGFcLe3S/mW7p1PS+aR
39F+mbtFjUgL3k6H6Zyw5OXvPFHZxH2d3e2po1ANtDqp0JKO+zroaN7nPqgpC6qfRxe8tSVZNJv1
YXtc3iESCKa1g8k56pfn1VbLe0jGlyycajNOBchlSDLvFw54Qjg6iwtIbD2wysehW56XW3nnI1Wi
BwciDJxGk127zVNzgEhD5rNhusoq0aH/Mv7daw5fzb4ISNnpXz4clTVM5jFY99VSg7VjZO19kz1V
NH7oZGftQxCnvCkXfQdytei+2ctbLBV7tUalZuCh2lHpn5MhUdbwERFwdCGGNCRzLHw1XkzueCTV
GQN5hvyxSDubDMt0qnSQL4qB3ltS8mUzZHr71pkYWxeOcRoS9bZSsKoRKn1aejZPMYzsGzEs4j8H
fRcfrUVIvRtmYFJBvOrz3pZrAt8GBkrm+KRVl5G29Ot3AzoU0rQdffy+NEdJUsC0TfBgpjEU6/C9
3SyM+6l7GfXjH+mgmRzdRmoL9omtmXe2ksIN0eeI8IWTN9Md34ad/mQ7qF6JpYMqtewqewqlLLo=
```

**Comment by carlosefr** [comment]
If you have a preference for t-shirt size, we'll try to honor it if we can.

**Comment by nosuchuser** [comment]
@carlosefr L is OK

**Comment by carlosefr** [comment]
Hi @nosuchuser ,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to org@pixels.camp. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (carlosefr) on the Pixels Camp Slack.
