### ISSUE TITLE
#forever

### ISSUE THREAD

**Issue by naps62** [PixelsCamp/pixelscamp-forever#4]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt.

This is my public proof on social media:

https://twitter.com/naps62/status/1305455711154049027

### Encrypted Name and Shipping Address:

```
U2FsdGVkX19dHpmxfCBcK5bXiCPBoG43ARqeo4BZSRBxHZQIW3JusQOEEzCtuM/P/Uu3CEVMPNDS
xoYhIlBotmLbSuA33b2IvR7N567PqgG37nkqTKVKZH1+sIrD655v
```

### Encrypted Shared Key:

```
u67iQPuaBDiq6yZcwfa7g+sGXJq616F5XADhN0uiDaBFj4IXlBCLuPu1as724g8hxdpN3NWzwg+Y
2KRwHh9zeCV1NuWzMd1eh2mx12PzPY/Z49aPLuSJopHj3eNV0BJ+232EAHxySRoXselPC8ERvxJ/
zukinXdHxCZUKxlrV4G1lp9Ztbvun+xbka/Nr1QzHDaqo4oRdyYrVprU4nGSeKBhe5Fdvc5e5OdD
ZyYjt6NQkVBcCAU1XlXLPxnLk32BSY5NM1tmVREY0aB3138lPbvskRYRTbhOUSd1KiHfd1jIs6AR
NSNH0HSOr4yEGUxsWKo45McEoDPifwtCANIxaxnUhAwx0CbMFwePvzPs0wJqF/ASnAXF+sKQ9h3o
bkNlG8nTt8nB6VwWFvf/EbKVUIM84//qUTp5dYQYM4XElZVbpx7RpSvhrkcfWLzZfLNbr2iaBP6B
kJuNVQDZwNJR2RlkOeQ6gkQyWqALZ/oGp1PmZYa+GdNMZFaPhxnJpyMeNARRQuAn2GrKNCnstBXn
fjNoh1ZrHMg5iXcv8+8o/sSyMYGxNiwZDhSpkgfBsotEzfgwoZLEVDxrVYurgEj5JTyNNkpUzvnh
zdcHyZUWR2gxKUjwZPy/6R6N+Hp0S9hI3lKuEoOE9iVKeYw6SkgQoxSx7oo8GtJNSHwTO5ZSADs=
```

**Comment by carlosefr** [comment]
Hi @naps62 

Can you please regenerate both encrypted bits using the updated information in the README? The initial public key was wrong and has been replaced with the correct key, plus the OpenSSL commands were updated to ensure (some) compatibility between versions.

Sorry about the trouble.

**PS:** If you have a preference for t-shirt size, we'll try to honor it if we can.

**Comment by naps62** [comment]
@carlosefr no problem. done!

As for preferred shirt size: S

**Comment by carlosefr** [comment]
Hi @naps62 ,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to org@pixels.camp. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (carlosefr) on the Pixels Camp Slack.

**Comment by naps62** [comment]
@carlosefr no problem. just sent via email :)

**Comment by carlosefr** [comment]
Unfortunately, the parcel has been deemed undeliverable by the carrier (CTT) at the address provided and has been returned to the sender (the t-shirt manufacturer). It'll be kept safe and hopefully we can give it to you through other means in the future.

If you have any questions, please ask via DM on Slack.
