### ISSUE TITLE
The Badge Master requesting a Pixels Camp Forever t-shirt!

### ISSUE THREAD

**Issue by rfgamaral** [PixelsCamp/pixelscamp-forever#40]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt in size M.

This is my public proof on social media:

https://twitter.com/rfgamaral/status/1305578256117235715

### Encrypted Name and Shipping Address:

```
U2FsdGVkX18EGUGK5BSwrzk7glcq70R9IRKEXoR2Z6RJYuw0ufNwTuLaKG2qpFWatRd81p6iG/iU
TE8MoxpNG1hNCLCL4CNIkS1Ykby3sA/eIGAZDrooqYko0poB5rvxw8jQcQSJizgwhRkQelBjAg==
```

### Encrypted Shared Key:

```
O/6Ng9y2ysm8SyGtsN1n9kGdVl5gl+yR68ovRduuxcHd39GEKK3fBOMJh3sdCWZlRQHG8chrLc5P
Tjp4E7sE0ajhnPK/45brMmsGlykLZCbUq/75Cu+IvQd0tUYdKN6ZYsjoUSyh/4EJCTfzVpaldIWF
vOOvEI2kkuCOh6LdO/d51Ga2PMWjCpsPUi4dGSPPKsfGQX9yE4Dlf7owkFDvcUbHYjl18A4n5Erv
4msqIszH7fbzFxUEs0my1jw61HHm86kBBEBm3N2w+Jmq9RXtO1MG3pWGU1/Leldpx3i8l2Pju2qi
GNAnNdVlyrVa4by9v1TNF/t/7/08C3s7WIyfVx4c9VVFQtg+8BmQA8Cr+Axw+3O0Qt5CoxpLHazB
smjax1uxp8whahhct4rsztAry3bxJaFaY5/ek3EJmheI1o3GTPva1IwTs3Gv3ypcQXcphzDgAe1v
TxLxYa/kdKUaB+pUUE1xzAYP6SjRqnqEFqwvzpJL2k47caM8mR7Zqpatc9heHi0UhiVrOh/ahz5b
ABuyPz2BOW38MWTYIDrEPZjdjAt+6qaNhjmkgFkAj1LxRBmrMf99tcb3i2kMXR3WvanzixozWvi8
EV/SXgfad7foNGvfAO68WAdilyEi625IZbf3pIMtQ3VWChjElJkLDxldc1uhmNFTMn/SghnmIWU=
```

**Comment by carlosefr** [comment]
Hi @rfgamaral ,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to org@pixels.camp. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (carlosefr) on the Pixels Camp Slack.
