### ISSUE TITLE
Pixels Camp Forever!

### ISSUE THREAD

**Issue by jfhenriques** [PixelsCamp/pixelscamp-forever#41]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt in size L or XL

This is my public proof on social media:
https://twitter.com/jfmhenriques/status/1305607633777418246
I guess there won't be nuclear tacos this year 😔

### Encrypted Name and Shipping Address:

```
U2FsdGVkX1/3kVjjzwpg5zSLOJaSv5/7K0QhnvDZM26WLnzHdc2nRHRR3a2nx8OQFfHXJWNSq6g+
NPjMicUfMH1WOlBmOKnubZA9eNndEIn0+yOhsEVsQEdDpzFwZ7ihJFg/ltY/PIzx1EVvPPEYKw==
```

### Encrypted Shared Key:

```
L2m5AIR3Us4aVOY0UEOaxJ5yNiu5yEjRM1ImMbnLjz7H+g3wxzGmDxjQkCHL5czHUyZXcDdyHERJ
umZ3U1P+uIDxqRs6Z6ufFiF0cLBnQpQE2/4RfBdwetISoHhNhvp9xV2SzZBFGVmjSecxgfz+o8r2
W2BcRSdq2Ia3Yps1OgOo0SHArsX6l/mI2J5u5Nvk+hNRKa3ncOD7xfjOLUXwbGcC7izmVjW2bCpV
XYaSfPwvsU7yHbrIMXWoOBdRA1WBxJX4je5cKHrIh6SI9OfzyiuiujMkmFv0lXtnED6NAjhAbCAT
MiGc1FQygBXu6aZw7K1SLJd7gzML7FMPMYVCQzKEE1W2uN7UMKA5DX4hknDtltmjoRwl+SpGOPwG
XxGO/eM5sZuGkQqMYRvkPQ4euQGNKwo1Wzy2kyw+JJarfMaJI9zmQ7IUzMd4Lkf4hbXFgN8luDuX
UUESnxt54D9GXcfDx510/SZOToB+C+bFcHG9VMdJjJ7ii5pUd3o7YKKvQ9PCPfwzMjbVFDBReWIW
NOw47ebiaceq9/IeUCz/ZN56Iek5bTpIv8tP5TUjemzaX9/CMd8FTQw2juM5A90dDvE0JqCss/SO
zoVeVs3+eOA9ffJ2E5sPDjZaXCXYR380ZBwCXj75Mi7/YHNiWQZ3bfZysGD1wBiA20DUg/wJN60=
```

**Comment by carlosefr** [comment]
Hi @jfhenriques ,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to org@pixels.camp. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (carlosefr) on the Pixels Camp Slack.
