### ISSUE TITLE
Pixels Camp Forever

### ISSUE THREAD

**Issue by joanarijo** [PixelsCamp/pixelscamp-forever#42]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt in size S.

This is my public proof on social media:

https://twitter.com/joanarijo/status/1305603171612585990

### Encrypted Name and Shipping Address:

```
U2FsdGVkX1/G7ar3cSJZq70Dxm0SxeJlk3UpzP1gpj4ymcqrXKOLgUL7PmE28Mxv6WcbPSQ0jHvk
LKFFNdiXOKMSiJiFjyWP7/X3OKcs2is=
```

### Encrypted Shared Key:

```
R8+ycBFdGhHJA6w5keBqM2x0CQez5yiKHO0/vkO8IyI3OPz7ssQxvwqFEXmdVElQrSnRAGwd4tiG
2bZYcPZefTqZJVPfPN01GYGZt1t8AzjEkDywDGrGNQ9k5ROAVNm5ZUXY3OUPcgncg/+6wkoxIYGc
F23iBlhpCQl49M0aE+NIHIxB60GARe5DfkF2b//EcsBdSfyeFcaaLGwmzmSe4EREwoosLZcSeQEg
gheISUbElkZhA2kVPHBlZFzUuiGvjVkcxPQ6px4tcPu65I9r3oUCFtpuc2F+gX3Crebbn5LgQuin
N/qNC7mYJNUstS6HBSEGPOxqBF6Ueq9tvWZLxVpRvQvGnL29QsFEt8QFOkcPEaJdKVNeJLqksw8G
LYN+q5zSwACDo1D+0TOrStAEeCx6KKzurCPyoEjDVx/FCASjnBAYC80QKhsepLERzt6xcLIIzlqi
giqXJAk6lEV4MfCca1vBiQYJAC4oMpZq+1UpFYV7ct6W4I5v8x1svYp32kJ+Ng1dXLa6bKYuVRMY
2l/ULN5fmQVu6anOjiuV/06vnTOgLNbcXnBmdmOfN8euxsZLbMYwpOT56wCoKta7zgNBhxSSSfNG
cgWQPWOWCO3GREpEasJIJlqPHv8zlRMxZFb574ZvPm3J4Vd/AYLaunad5e+KtdbaKro6poawThc=
```

**Comment by carlosefr** [comment]
Hi @joanarijo ,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to org@pixels.camp. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (carlosefr) on the Pixels Camp Slack.
