### ISSUE TITLE
Some goodies from a previous edition! 

### ISSUE THREAD

**Issue by abmantis** [PixelsCamp/pixelscamp-forever#43]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt in size M.

This is my public proof on social media:

https://twitter.com/abmantis13/status/1305572962918162432

### Encrypted Name and Shipping Address:

```
U2FsdGVkX1+NggIqgd2rqUbUb843SadrjxJjgqX6U3rwm+hLOAOnuxM7hpmYsEfB/VZJvWZv6nHG
1n4MvqKWeHcQjrAmuE98kJYbLkCKW3yRG5MD2KToi8MVvtvXKFVI6F59qGQhIbtTcWn7inaccw==
```

### Encrypted Shared Key:

```
oI4LjHET3PZi/y6P2/XQfGAzUCR7a0txpj+ufzz2oDPtupF30Dhl5vPDzyHc9HXXk44Zkwk+Va8t
l6un/HZprA93Uhehw5PV1CZd/TvF8I0+Rmkp4um9X4ZaWx5YffytTLNpXm8XLwxcHyKfztMGiBN0
G0TrZsr/4HaTNWz3pKKzx1Xlmj4sOlUTK0RMCG6r87Bvx/n/UG8MibEGhbd+Kz26Sk7Uq9IgmwPg
33y77Nbk5Fc5SV838gG+Gu5QJ/xEN3JUV/WKHPuN9l6TYyVhNPPtQTm3iJsrKnsoxXy40Ss0dZWc
Rg7brOal8eVjbdSobiFIsh9iWWfdM7GbpyOwFDQbhU1+O2FJaxODydtuZBfQLjkyb4545r1p0Za1
1oK2X6/NKHGYpWxPJknRIc9xYfkNkoJ8rsD+P4vKOFz5pfetp0MKPL64DQzise+6FxBh8ks52Qa5
2h97BYHb7CWqi4s+ZdJw2upli7ckEEsZxFk9nYKBXXzYmMpWze7M3qnGWLaeqRn6F0Z5IKUJ3527
Gp2o6Xg9p7q8xCnHxobIKOKmh0r14eDZ6o4TXEQaXwlQ4+EthXn4CXeqpR+bvBMuR2MvpjLBuoTh
cOhc5qS6vA/wyKQ5T3XSPaGKQZ3B1MUz17/Alya4WBC5dYRwltLs70ytCLWGtncuzcpm8LezmqI=
```

**Comment by carlosefr** [comment]
Hi @abmantis ,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to org@pixels.camp. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (carlosefr) on the Pixels Camp Slack.
