### ISSUE TITLE
This year t-shirt challenge was really short....and easy

### ISSUE THREAD

**Issue by bacitoto** [PixelsCamp/pixelscamp-forever#47]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt in size L, or if not possible XL

This is my public proof on social media:

https://twitter.com/FBellini_piupiu/status/1305675869214646274

### Encrypted Name and Shipping Address:

```
U2FsdGVkX1/oboSQRar1hXwQJLKwMw1h4NEUFeONvPMYkxHUcQoN3ZuonEsCTxgljk1I6iG6KJI+
MDbp51e2ELIzgorVl5BqyF6vhAZIFY8fellVxE3eygF7d18R9+W+
```

### Encrypted Shared Key:

```
athL3XlgPF9cGt4KEbpkWGjw8O+/qv9Yhp96Vqlgca5K4uos1J8M6EYniqivM+Io5fRhY56Dq76W
W+nOy5NrhcEPLIsmcEtpWkWpFCn2PSa3D7riPaCFB+bOLw5IaqEXQLiMcuf66ufMSo2spSFFcQL6
A+Ne4eouJBYSitVsTenriJlw+LqngO3tLDrsg99mlf28ycAr1LP5NiIKMztNi7C3vONW7MQ3KR+3
wyDN2cyWcRb3+3o2fIxQY61UroD9i1mpJS9rYrlY1aPx85ivG5ggOdGwtGehskXjU7jVULfoEbqN
7m6cCAYFP85zD5KmJxzuGMNGRqOavSpJpA8AdfLKlWAqW37bxW8YCFCDed1Omp7e6G3nSptlJ8G3
xvc9srtuzoIIZE7Y9upNl77PiBI0sId5UdpxHbOLCWGf9ceFbaNOCvDzCyrJ3Dg2OVaDLofphPFI
hGjDGUqS2dpot8Ej9rCGHl9y/PhcqxfQgSR/JAJlQXlIo3Cy2gBRTnf9UVmXdmjjRBPAMoaQANEG
e6PMvIa3VQPK9Hs/ySPv+pPmEjPLANTvv1gGFke//AsRauctRM+i1dtCUganOM083kIlH9tuC49o
H5iBA9JZOqeIG8okkU1wgl+H1dokE5UOk28Vff0FdDM/+VvGotlr58a3g73uk/WWoBaeuYNTJRc=
```

_You can edit the issue and paste the encrypted bits later if you wish. They're only needed after the request is accepted._

**Comment by carlosefr** [comment]
Hi @bacitoto ,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to org@pixels.camp. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (carlosefr) on the Pixels Camp Slack.
