### ISSUE TITLE
#pixelscamp #forever 🤗

### ISSUE THREAD

**Issue by dcaixinha** [PixelsCamp/pixelscamp-forever#48]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt in size L.

This is my public proof on social media:

https://twitter.com/d_caixinha/status/1305784172330582016?s=20

### Encrypted Name and Shipping Address:

```
U2FsdGVkX19XH1T95X/EQ9d9bn7ekgAqWb9azrQauyRHtMWXxAqHGNvnyEYDAUAW6L8FP5WvX0dh
rJ9M2tDmuCtCj62t4XORXA9prIGQTvK1xj2yq6jMXkHyOof2ZTQG
```

### Encrypted Shared Key:

```
Z1F+P/v/TBt4f8PTSoexuPQIhrmZLRvav06R6Sf/h0eOP3YEkPgweRBBOv0wa0+zvLlyFBvNbQZW
4vK1qp6VytWfjbeONigTPs4oGm3Qf+8GE+cJVsd/fQTnkQVA5Vazrj+HK7L+VQ6rk/HVyFGpFcmB
tiU5fQJa8QVjynGUvmXsmg/8+CSKbQtcv/VgyGsXkreSqYR1I6WXlalhHq2B0o+mWJCQ4Ce+p6B6
PWwpdUB/KKZsG3d2vHjM63UEtXwPEsiPnYJsT+Mis4dv9exdTzZam2tQbh4VByvwdh4VLMlGynAE
I3jkW0rAYBiYBJ3jReq8NXT/n5qEVDD/o9sQ/DKUWFUy+nqXIgOBSaf9hFXdXK8K7kuPGsp/tyzV
fepwrTHic+jXSgnPvGBR/XDF1x4N3gE12O2y3iawR+qXBwJhSXHmVJ2hyxKlob9593LBxxlqRa5r
ANDoH71b6uOERhIYBKq1yYGZW/jiIuqWOUmEz1kZvkSbKVuWc5APDIaGaUaIUxLbft/76W47zvqU
Y9o4es/+EYb9EbWNg6M2rTGVr4WO+8liskcrIJQwNZCSOQHVMHKRQ8XlJ6qQcz0mtMlKMep2Xdnb
TDz6Kku30KAtovJkPjl1zDtvXWpZHTqUbSm4AuAg/8VwZ9+25rDOKEKhl2kkLsEgjWjfwqy73Dk=
```

**Comment by carlosefr** [comment]
Hi @dcaixinha ,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to org@pixels.camp. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (carlosefr) on the Pixels Camp Slack.
