### ISSUE TITLE
Turning Hotness to 11!

### ISSUE THREAD

**Issue by wisewolf** [PixelsCamp/pixelscamp-forever#49]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt in size L.

This is my public proof on social media:

https://twitter.com/loboastuto/status/1305788700446601216

### Encrypted Name and Shipping Address:

```
U2FsdGVkX19uIbzBVBhZeXuPzOL6CXJUZCUyKMk5qD892YJjTXzVEqa+CxESTBE178V1yRnCe/FQ
KwYdcb2IFeYxrx4RkpL4J+JUdCf7c4ywFq9TgRaGnLe6v0bMoHs7JbX79t+8H9BdtPSgC1GcAg==
```

### Encrypted Shared Key:

```
JZKsN0Zj4uNvhAqnBnzvYrC5cH8Pm78U6PaAy7IzgzRbyQUybE/eigbS0YHQpj6NnVDwCNunWx8+
M20earg0EItGhhcisH3t9B6YQtTAwguC+kw2IWE1JPoFZNXqFRyMNq4VGzx0v4IwxxwDcadCDeSH
4tKf0cXxF0mNzNMoV+5aVD+XaQ7XBRryWu3DX7lms8ZQcvMV5iPoRrpHJT+LrVM9DzX2NfJoWKnh
Fn88UgnuxhzwpxF8Ew7nPmMVk6kdQryRRzcxzeL4MPDKqYsXa9caGjRSfRqZOSqmfASgQNtqhNWv
jh9r9vPKQfwg24j7vmUA6uKIo4YXqR0kFaw5M9f7Ko0lhZndqH7k3jHY4TE9r94yi4aZ4j2EziZg
jkG0l4N7f4dsU41uqiTL6Z+a9TmGop6gpJ3tJKZb+ztGCgVnYjBAok0KrsiyvlyuZ6ZXq/7NKWUs
glV8bFNi7i8nmyXaGIyTguGke26kXrAMlh7ZwuPiDoRminLfySiZbhGc7+6YjQc1BdevKR9OxsvP
R4bOI5T9eLFGlXP1gcRLigTbVp1o/Ks+S2ea4Pe5TA2JOoqUHpwaEE5s4wjwgzzoa/gl56a0wqz1
9cbrK7tUghK75Ykqiy41FC9HiYalZIb+vqge8Ol3GmCR3aXC9SSHwhwEg7GznCi98pKTZMjgvaE=
```

**Comment by carlosefr** [comment]
Hi @wisewolf ,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to org@pixels.camp. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (carlosefr) on the Pixels Camp Slack.
