### ISSUE TITLE
Proud Volunteer at Pixels Camp

### ISSUE THREAD

**Issue by FilipeGouveia** [PixelsCamp/pixelscamp-forever#5]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt.

This is my public proof on social media:

https://twitter.com/FilipeRGouveia/status/1305459666189783040

### Encrypted Name and Shipping Address:

```
U2FsdGVkX19JMIXL8+yJhAPzcjpYO3fSYWMjHvNh6tudL8W1k7WwSZWjrNys/C5CHPy+TZOxDj4j
pgwGVBaSdHq+R7zKICdLAeVJpb+HoQnwc6IqGGSsHdg1evxR9awN

```

### Encrypted Shared Key:

```
nO0ensCReyVqWYu76HnQ2a7i7l8+hkdozvPN79jSSDSQIA3bW/uqIsjm5GPKPSMb+AIgh24/7EjL
AW7uJKjNcS3YuOGtDDs7hkj6/QUi4hCkoS8OzeFH52gXgJw6AgJML82KewiOUyQN/Xgl1+w5brzZ
fqvWYy5JklhS05PNsytIPpJxTW6Dhylwg6CCuf2cW/qVIO0/zHkQZtCwBGFt57ggqXgeXttfOhLI
amEX6sdikKtqXqDiv3e4dBsnG4LDtHw7Yk9TdOPbvp04p6G7VzE5BYuaxqVHIoq6Q1ZXkEXXPHE4
bZzFPzU40DVP85rqjxm1xbJQ1mVLX8WnzV7dc8qhtu6fKguENpD3yHTBCw9imnP1ySPLC1AgvvuD
v8OiiiMyvSteXtRdlTcL/Zoo5H0lqtZKJjqAdUXl1TZbXVjlJfmfAA6P50MCoaaPdEcEU+ltfoPy
hNRMXOyqCej73o6DqSESSVSQcY6GsQ+0P2zSrKTD2GYg0J3jX0ieMsjXtJVypzG3pbtK/qx5tN26
CR7yH0reY06Xj2qyd+CLNjw+BJ1DnmMrgMw8JXRxgVyuzrJQcj7pUVo5do5VA5J+8V0jdhCNcUAK
/qTYTxSn1seQAW5lBvrHI4B75+nhpB46yzpgI1fBhNXzh/6K+Q2Ak6X8fuFJ1fWAo9wSf4rGF4o=

```

_You can edit the issue and paste the encrypted bits later if you wish. They're only needed after the request is accepted._

**Comment by carlosefr** [comment]
Hi @FilipeGouveia 

Can you please regenerate both encrypted bits using the updated information in the README? The initial public key was wrong and has been replaced with the correct key, plus the OpenSSL commands were updated to ensure (some) compatibility between versions.

Sorry about the trouble.

**PS:** If you have a preference for t-shirt size, we'll try to honor it if we can.

**Comment by FilipeGouveia** [comment]
Hi!!!
Glad to hear from you! I hope that all of the pixelscamp family are well and fine :D
I've updated the info. 
Btw, my t-shirt size is S. I may be a "veteran" volunteer (never missed), but I am also probably the smallest one XD
Regards

**Comment by carlosefr** [comment]
Hi @FilipeGouveia ,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to org@pixels.camp. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (carlosefr) on the Pixels Camp Slack.

**Comment by FilipeGouveia** [comment]
Hi!
Sent the contact information via DM on Pixels Camp Slack :)
