### ISSUE TITLE
#pixelscamp #forever

### ISSUE THREAD

**Issue by FJSFerreira** [PixelsCamp/pixelscamp-forever#51]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt in size L.

This is my public proof on social media:

https://twitter.com/Ferreira/status/1305911492538241025

### Encrypted Name and Shipping Address:

```
U2FsdGVkX1/vad9mJ0mKIsJ8pRPjcp/VZd09zOs7hUOnt68Qy4nH459jd8ETEC/mePWR74/hetu5WXRQ2oR+0a+ebnUU2La+2U++UOB1lMc=
```

### Encrypted Shared Key:

```
DHSJ8lGohLtbX+KFWrUJC2aG6xFHJ0XmyWL2Eyw5DueCpx7rmdcpiJMYnjthw6/cQq0UEQWqdZ7AMPJbGGvqQPXdwZ5+34zVvz4qaZ1JFjRO9NyazHzw0exbuLaXWcuJLfrQjHfRX+qNRA4FekU8Ll8Sny9I/8n6sH/UyFAOKMFOuwyDemvtNQjOqo9gui9D3DrCyjQAUrIJFF0bcpwAh7L9GZUV5oTIYJSWlgjH6XU45nqQrwND3h/X08lD3SbGvib0zboz1TN28mIjcBLu2HJgc7ebLhdBTKUcJOaPBqXUI4z9w5R7F51Mg+bVySz7BXeTofmvOgVyshLwoItBZUxq7lhRr6GbdUep/WxL2mbMhTwtCuNTVb7sOfPFpHdQnOsXBlESphTvCjXBo1kKuIyx3ut0lMTd71xDXDMx2J4zpHKgah697z8oqNQdnmBibihxcFtttJmllnKVA1UupZpVuaMdKMgZLu+mV6lnrcPoxBUkyGqBMJTISQYxFCq43H7qibjYGVSVqe7Vz/q/uKGwaVYoUDVNNpJR7RL+hJUzKAk77CwGqe/FVw2HuoPMxA+ShSNCjfdfOuQvslgpnJz3G/wFWkMS1SR7ktH4r9AJO+RJqT81dRV/13o0u1xfDBkc4HP8LNFRdnq9wd/TAo4a2Ge8RrCxgnJuWlsywgA=
```

_You can edit the issue and paste the encrypted bits later if you wish. They're only needed after the request is accepted._

**Comment by carlosefr** [comment]
Hi @FJSF ,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to org@pixels.camp. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (carlosefr) on the Pixels Camp Slack.

**Comment by FJSFerreira** [comment]
Hi.

Just sent an email with all the required info.

**Comment by FJSFerreira** [comment]
It arrived today. Thanks!
