### ISSUE TITLE
To the moon #quizshow #forever

### ISSUE THREAD

**Issue by jmotp** [PixelsCamp/pixelscamp-forever#52]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt in size L (_choose one size, and we'll try to honor it if possible_).

This is my public proof on social media:

https://twitter.com/Jmotp/status/1305916140980514817

### Encrypted Name and Shipping Address:

```
U2FsdGVkX19WcY6tsi1G193qrumigI7pNmhpS0oq1PyXZMJJxTDpE0maQD5zH50EJQyBr8wj/Xix
laK1v1IXO1fOixGBak+gr061hAc/wpRENpeCcQ0qasKD9RkPq6po
```

### Encrypted Shared Key:

```
PTzgdVcGpXGhZW91vIUo5d3VIKLzjcmYuJDQMNFMjqsLJZmi72O2HBXXfDfG3TJsRDx31mtnUIpN
C8gEiDrc6qllvGArYU6NuT+vaQT2q9kfdOLM2dRPU9ctdVcp920o7HbO4A18R7+YvrHDZ5xSIPpE
4jziryCTceG9k8zcr4hzmAfs4l48XIc1lt9GKrCWnGTWo9H1T8RlgA66Dgg688N5sVetiljerHhn
gX1NU5ybYaa7CbuoaNu4WsrIPMCyAA3RfkS/5QakE3m3sB0TkvQNKdnWjh4xmQAufAAE9oUC6gjy
TwEhjK7s7VtSVNyjOQYuB0XXPl2VUfmdok+kPGf+rLdXBJMNoS3csVhDXCCjTRMC4vyD127EUiq+
c1ToUsin2As8ka3GtjllxlSd30x+7WHsBzoHKsllL/8ZhsAdZoFCfsmc0E3bY135Cvd2EyhauGzu
MwA4a18Pe/AncjAhfV4feNPpyoqAi1eliuCs76kDAfOJhifrPX9p+0pbco3JwMw3zsOoeYn2YNZO
1SSF3Olm5VN0JPU6wAlAtvCRJexiCh5slzhIoERV1QzhDB9SKjYslJ6zItVxm+FqJs4KR0XQue12
NkfR2MfTXmEts3hAODFmvdB+p8voYR3jzyNMNUpP5svu7VqL/+p3FnCYBbmu0YskLiGVH3P8E8w=
```

_You can edit the issue and paste the encrypted bits later if you wish. They're only needed after the request is accepted._

**Comment by carlosefr** [comment]
Hi @jmotp ,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to org@pixels.camp. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (carlosefr) on the Pixels Camp Slack.
