### ISSUE TITLE
Showing Pixels Camp some love 

### ISSUE THREAD

**Issue by soniatelesfernandes** [PixelsCamp/pixelscamp-forever#53]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt in size S.

This is my public proof on social media:

1. [Insert Coin @ Twitter](https://twitter.com/SoniaTelesF/status/1306188042890366976)
2. [Insert Coin @ Twitter](https://twitter.com/SoniaTelesF/status/1306188247001858051)

### Encrypted Name and Shipping Address:

```
U2FsdGVkX187MBe/RQhDe5TtryW0DDZU8rodiT8tXdfQqhQNfxHluPFdq6oYCQpMBQnRxvoAL2lO2akFso3KsGTr6SondWpsBKHWvd0P9O7o+inNPDHXbWVo6Ffzrd+jnR4Ed/Ue+o7sKiVHIjwEbw==
```

### Encrypted Shared Key:

```
PI0Thpb1upUuWV0jbjnBMd+MpaoTnV84Sh0OVgFbD4LTUAF9HEGveLhUOkNKkwl9zksOTDHz9T148BzSqnqttDpWRUuSdbZg/UpI+rdiG80Uvaj3YsZ5spVI4UpanqxBoM1PvPmioalTsndb9OzzyI2IvY0QFCTCdtApu8tdQv00pIm8604zXt5+gQ2FQ5O9zZ6NL/CM04eVelZkZHlu1n2+y9n4cAGAAqptHlTc04Ieho88leOCRnNKKMdiJp2hapYv7254ZSSXVBnLBAVCgeAbXHodyr6AfIQ6uqMy6wZOqrNT/JhgorEA6xHxl6ypjZVc9rBO1ZhEIQ9foSJ1HCPYdGDW5YsSuMnR/IXWp92FZeO1JahhAms3cx1NpI6lPX4+GZ2LzPGg0iW48nTW34uasoSzT/nZmgYu7DXKS7ukhXM7CrlI/fQXc1wAh0B5uVYgnbYWi2FnkmFyJqIZTLghuUUyG1BvwKs88S4OoUeHYkYYs4/LNrpODCzUlmUaMqWIEVwXPB8PTAsUC3+3vU1sYiCZLA7ZE0YkHF/A8GsgktFt36WiawtOTUMiSVInkYlIj/CW4YuPYEyQYEDShNrNorrosGLktQhBdgdAWH/OFEv3uZ6CcXzBuqMYxiUA4XvOS1S95o19pnzPUVqDpZQVwKG29a5mZd0EGOu586s=
```

**Comment by carlosefr** [comment]
Hi @soniatelesfernandes ,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to org@pixels.camp. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (carlosefr) on the Pixels Camp Slack.
