### ISSUE TITLE
#pixelscamp #forever

### ISSUE THREAD

**Issue by aclima93** [PixelsCamp/pixelscamp-forever#54]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt in size M.

This is my public proof on social media:

https://twitter.com/aclima93/status/1305541942302957569
https://twitter.com/aclima93/status/1305585125082759168

### Encrypted Name and Shipping Address:

```
U2FsdGVkX19/0Ju0fW5mbOtaPfd0XkHbaKEVTJFqWP07V49wSRm0v4jiFPu6ZJIluP8SztguV+FhpqigOBKcsSqJdcjGE9y1tNY3Pcrsi9s3LbrR93+pMS94y2kg+sUpsrRQkDqFPZ9+kG81a/dq4w==
```

### Encrypted Shared Key:

```
vo04hnB+uV3y0nVaGtY5MFR/lC4NKxcLncFUqvNG+W7dvkWCy4K/1p7aEYQo1JUfuWSVw6j5zNAGzYS3+5o5GK7v/I0dNtGq1YsGrqLrfq6vZwL4pgP/li5wdxwzAPTz9AkBFCTU+fMz8/N/7XwBLOzJZAn56PBrvlW7mQ2alcRyObnlPsP2lH/JoFYrk5alLnfrPwEGvLdNO8XuZDCjpoHAyX9IA7+hJq3yE5a2mZdJx8l3GlzvpX3WsZTXUkmX5YpPTgTOJ+LXPQGXSw3HkJ9LuSHZ74bcBKJdIb8af6xJjCuH0FyuleFEwTNLwLgur9SKMU11FLStTJJGy3DlKrzKEhoCGnzMwHggp7G+OdLJ3y3ZpmejpSS9nm0hCZXMpPc4oXAcPW4v6bTcWjAYw+XeuKGryjrosz3f5upUvzYzGqc3et0ttWB6x6y6WpHO0jMAAYXtDrurhu/u+DT9VAKTMLVAQ5eKZgfmZuSWvnWwYYLLv+aPlss4jcCMrDLPU6kkS+6eVXnXcRNK+VyUCn5G0d85cnsakaANu49wYgIsZafxBL87GgD5ZeGg1Dq3QYRnKSmAealM0XDmBQTnsfIClZS2opgqs3BAYrNcu8e29GzYl8IAmUgSC5YXS12MjWLggbxbe+x8PnSLm3wdXNaX9V96RgHfHwafwlP1KIA=
```

Looking forward to eating more spicy food in the next edition 🌶️ 🔥

**Comment by carlosefr** [comment]
Hi @aclima93 ,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to org@pixels.camp. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (carlosefr) on the Pixels Camp Slack.
