### ISSUE TITLE
#pixelscamp #forever

### ISSUE THREAD

**Issue by JoRod94** [PixelsCamp/pixelscamp-forever#55]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt in size M.

This is my public proof on social media:
https://twitter.com/jorod94/status/1307291727741452288?s=21

### Encrypted Name and Shipping Address:

```
U2FsdGVkX1/MmSc91UTpk6oFQt0c3UnevF8yCSGDrs5ci2/+UvD3SVO5ijF+pvXc+3EymeASidbC89RvBGjDYjFhNmjNrY7WRFn3ZZc1256xd+pNLxSPYHCFt+k6M/bQnSwd0ENWH1x+HHs9tAVdSQ==
```

### Encrypted Shared Key:

```
jgthXn8qSF0rMOHQz2Z28rSZ8bU2oDaLyJXyfuyH7X3vJDPaxAXlGOqD+vZ1N6557POE786BwZLr6arqdU9/jQsWXfIslaZR5pDMB1jXmVmwG39yxK/NWUEKxOX3KwVnhkvREYQ/QP3WUmweW8NFLxjxFcvhEJvX+fZaWjrwWFJysWINOUXskIoXpmePMRh6S15gRtgO7O4NaCEpxEhdI3Z84MTPpA78MROQ9w0ttETaWhlZD23jixPQxrhNnEhEbZWmIU43pWDt3hQ93o7WODO95Qsa9U/ESoH1dJpuf0z6361D+s4VnhDNxdAAPogt+ilCm9Us6iLSVd3x1+iQ/J66d2Sh/nRhjN15IqN88X4VRArfQf2Ag6etdi0FhCtwBRJV0muLuhbsfvm8NHCZg1Mhs69IhpY15dPZPXhQget5vFwecWpE5HL8rHUk6CjAiITj5vkNeHMuh+QBGwjvydACi5TaVuC402u90v3EfBUuRwfue2kbmVegcOcU6qeo3o6qGefXW6wS/11mtoUb/6/Ko+i3a0Iq/BslXm6CTGAYhSTxb5JmLdk3o0zq4mLlrBAiZEW2mML9XeHDnE1LBVtkF6DjUyrzG3DTgf0oHqTP4ev6ekqpCEPIq240vt8IQweOhKzNkDcYeaBUojViyjAlfmKJdUht4cJiZ1NXBRQ=
```

_You can edit the issue and paste the encrypted bits later if you wish. They're only needed after the request is accepted._

**Comment by carlosefr** [comment]
Hi @JoRod94 

The rules say "posting a photo or video with the hashtags #pixelscamp and #forever on social media". C'mon, just do it. 🙃

**Comment by JoRod94** [comment]
Sorry @carlosefr , misread the rules, thought I just had to share it as an attachment on GitHub, proof added.

**Comment by carlosefr** [comment]
Hi @JoRod94 ,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to org@pixels.camp. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (carlosefr) on the Pixels Camp Slack.

**Comment by carlosefr** [comment]
Hi @JoRod94,

Can you provide us with the required information by late Sunday, December 12?

**Comment by JoRod94** [comment]
Hi @carlosefr. Sorry I missed these replies, I've sent the email. Not sure if it's still possible since it's past the date you mentioned, but I sent it anyway. Thank you!

**Comment by carlosefr** [comment]
We already sent the numbers to the logistics company and used a number from a member of our team in your case. But now that we have your number we can contact you in case anything wrong happens during delivery, no problem.

**Comment by JoRod94** [comment]
Thank you!
