### ISSUE TITLE
TofuLynx Limited edition t-shirt request

### ISSUE THREAD

**Issue by cfpgomes** [PixelsCamp/pixelscamp-forever#56]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt in size M.

This is my public proof on social media:

https://www.instagram.com/p/CFNH9QQAA9P/
![image](https://user-images.githubusercontent.com/36174494/93369219-f5980000-f846-11ea-8053-9ad311dee8aa.png)

### Encrypted Name and Shipping Address:

```
U2FsdGVkX18bpItxQKPCmkO9Nt8reCL375tsBr5lTDCkw3cVccslVbO2G+2uBZ+F0FD8lS2CPew/
gDCSYhBo62meVSJ1tmnJQVy4PuzA1z3bzBqNZLNhbrSv0d2a6Bep
```

### Encrypted Shared Key:

```
m0rIWmJIzIvVXgjDNEO368UQZRrJ34JjjPN6FuCe25bnNVHWKY1oPBYnelf7bHHlOv59Zb0VnckT
upUgvQJQSV/Qtis0tYfqW9fvsW9BqDYG+H7o4YSwTZ0o70rhr4QqGRo6KFQR0OBJFNqS0mbEHDC6
ffmS0GnZmTe3uChABbh+AsVBakS3hsNiJMPjB6DVHU6NuvvoPhMt4qB7FQWYpu+zfj/gZIwH9X26
Qj/1wC46JHqJOOPx40ZpkUEbIp9pp66lfBccmEoVBzBT+05Q5w8QKypEZQNsGJbrdG/208EK5Urs
zDPwrkFFF26uLZOV9ivaaHMmIM7OIbBYK0/A5XFhMmY9KTIqIncFZ/ox7JjtfvNM8tSDsamjREdZ
1R0wBrXCn3aOoAr8MBLqjk6PpunRwEPKkOg5VC/P4B2E1UzF+LQCoDtlJXZ2ak2fPKfq5FgGZS5P
0zeVGsq6rSA8XEsf2tGB390Q6rYDm09J//pnpDCSlBXOmEV/pVLDa4YXBGz62KZnak/eAxSM645R
LHJQmeHQKZYM1DPCmCaixbxh3Hjzt6mnHyoN4uZn9cr55Qv0JF2OpGqBDrhoZvt9fmnxGd9YRZ83
fG1CsnxLmLWPFiG+7uNcPqnGPurXzpftp+Xny1GQInE2jBoV33nnOXin39n+z3mAjuARKaqFkxw=
```

_You can edit the issue and paste the encrypted bits later if you wish. They're only needed after the request is accepted._

**Comment by carlosefr** [comment]
Hi @TofuLynx ,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to org@pixels.camp. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (carlosefr) on the Pixels Camp Slack.
