### ISSUE TITLE
I FIND YOUR LACK OF PIXELS DISTURBING

### ISSUE THREAD

**Issue by hgg** [PixelsCamp/pixelscamp-forever#57]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt in size M

This is my public proof on social media:

https://twitter.com/Hugainz/status/1306278652032593920

### Encrypted Name and Shipping Address:

U2FsdGVkX18Xl+K+9EO6foeS+bKyc1wLb2axXEaU0aRC5HgAa+e11XH2ohbueRbrCkJa2D/wMLG++XpOw4oFlNYxwg9obqV6YKhucVqbAxWo6uSxDZps7G7dueI669aA

### Encrypted Shared Key:

r8X3d3P5KrMSp/kuSr+I37SGuQ+bE67JtXWCpY1d1ZQW6ZACqjJEqGgGzmUxkK3u0YKLQ8aVumR3gb1EXI9pxUa9tzpaUH9eOZ89dlqGiAIgcn/ZMrI1KRqpoYa/00TLbFR7oJATomWxpB/dQ0mEagJc8r0AvtFYImMO7CdIFoy5847VzcsjrIzlzaE0pEFzC4ejPIF4Log8bbx/MLNa0Rra2MEq5bVjzwSmIjEMHkqT6/moGfCucF7cHX3rts596jljpQ8o3e4wqVsuPwgVVDCD3HPDxsFyRH5xZ9qgRYtJLxyPGgBxZDmz+TYG+mYODdWvFH+XWs4dLPjwCk0gvfHwCqK4DuGPr80hv8UveHneQ8iQqZCn6QnPYTkUwrEnh5ACHNhUfssfYHCcFGquCOikrStmm+k8SxJ/eRFj+TfH2mucc97oykodEBrfjJwXE85aAaUKWMTw2dJEhSrH/dykjK4I8FEjurCA97I6AuWuLwbTVUIiijoPe7g53+TThaMd8nuvqwV18+76Ji+UDmmpO0UkumdVH4xTdE7MrrTRDMzb0dCt8WlksLbVRKGeqK4a7UqjII9P7N73r6EUAADKUOFIP5HKZKHRZGClQQSReEPy07RAAVeWdxeIRsIFHhmR01iwn6ZDrCoiBeaEaLxsiLJ4+E8VJvgCH/9foXE=

**Comment by carlosefr** [comment]
Hi @hgg,

We are unable to find your username in the approved attendees list for any Pixels Camp edition.
Also, we are unable to view the link you pasted.

**Comment by hgg** [comment]
Hi @carlosefr 

I unprotected my tweets, so you should now be able to see the tweet. Sorry for that.
Also, when I went to pixels my GH username was different: hugainz or Hugainz not really sure about the capitalization. Can you double check with that in mind, please?

**Comment by carlosefr** [comment]
Hi @hgg,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to org@pixels.camp. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (carlosefr) on the Pixels Camp Slack.

**Comment by hgg** [comment]
Done :) Sent you guys an email.
