### ISSUE TITLE
#oneofus

### ISSUE THREAD

**Issue by pedromg** [PixelsCamp/pixelscamp-forever#59]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt in size M.

This is my public proof on social media:

Well... an introvert picture by then, heading for the train, not very loud but [quite proudly full geared](https://www.instagram.com/p/BviJWk8lxyEN6VoIh-sDtzdypAKA8FN4MJ2gYI0/)

### Encrypted Name and Shipping Address:

```
U2FsdGVkX182uABM7zL5iZuYgMPz/8zXJoSTj/YYZhUCQcLVjXOEqlXBG4FGZgMQma2Mlj5goxhG
BM/OK5Ob/fjUZjC/5G22mlOfPXerPDU=
```

### Encrypted Shared Key:

```
ALPGermEDuRr97dlyDSXqQbyyc8NHDz7q777JVlvRFmhA23JKoqlqAcpsL9HOGxhjUchZeOFAY/p
2DGn25hq4N1JMKdThLFdlGtCrRSt8gIkAR5OyZ89eVRK431qC7JSVSFO/d+RfLqZTJ80IYRv/4On
xikwTkb5y+T50P6EpZWOtf+syGnRuJkEmDSKZiqdTJq4o21AstkemaDdIZ0+OV3Yf+1vNEwMaMHK
LZdpUCWkLtENiDHOpB1x1q366albjprL9LRq3fB5vyeESSUoKv6iVJrrKGlJPRfz79CBbh3N4Dwt
GnPR5CM6zu0LX+regSkr3zEbqI+lZfphmjlKVx+VBuer2ukYEYce8eRBXXOvN2QzRbxAaum/cL7e
G4it9sAribB2UHVNCelBqpVjnQnfhrV2Kkeu6pxD1PCebGlNft4yrNWH3ZyKzJpnz7DA7mJvU1pw
AFDuM5d2N4iTT1KMqQSpxAkokurQ4eLpMHRyereApzGGz0crYWEAtN/tNbqxNHpBomfeefh+HOlF
gRNzB1czAZb56SVlwZyz5vAAjZ/CnaeywXlDh2l2hq2XEyTXu+LdeQjbTKK4fHWTpw6str1076uY
IBx7Q6vIPW461Kstp3huuSBg11EWtBPABlOKjT8md1eD3SF0tcWBXuPOFwZy4qPR6pbvWeBZPHc=
```

**Comment by carlosefr** [comment]
Hi @pedromg ,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to org@pixels.camp. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (carlosefr) on the Pixels Camp Slack.
