### ISSUE TITLE
There should also be a radio for this tshirt challenge! :stuck_out_tongue: 

### ISSUE THREAD

**Issue by miguelpduarte** [PixelsCamp/pixelscamp-forever#6]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt.

This is my public proof on social media:

https://twitter.com/miguelpduarte/status/1305460855451025409

### Encrypted Name and Shipping Address:

```
U2FsdGVkX1/ScVjJ9E67GzDHEJzwktzGuEQZKSbJkyJ/hjWD4vqd5SardnRZ3n7/gG96d5kOJgbY
kxoUwyjybv9y9X9k311Y0meCLat8fRzfbpTSHHePZcPDkxhaiueF
```

### Encrypted Shared Key:

```
Q0PnD4ICALhYWKbecToZfxdWQeAC0Xz9JVbUsDMX89I7OoeuL8hCzk5wy4k7eCQlrnCFrQb6Z5nY
pyks3cQKxTCUiEEBLJ/MJ6Li8NTKdmwopfsvkZG5mhbwR2e0B54VURU7e1CfumezCpEhhwCX5sEm
zqkk+XEYEaWr5Gqpec9q6T3pD9inrx4ppp59AglR3otSRsT2QlxZFUwpafC+6ZsWta9QlXrknwWT
xWeaNTx3BkVeTeUgb0K92V6fT0fhGoQlNwkRXsmaapfxV80VnsrkyL/VZHlQLphRXLijNQ6fThNr
c5RSj/zZ0dbfQwdsJkxCWSta0FP//MeCYyRI5skW3t/ef8vTd68a4cNpBg5MHzg9hVsTjhj/z5KP
2S0Nu12Sl+Z+g9q8hB9yZhnX64RXqeaksomZS8yUZQbPU1EOcwR4Y8U001oC1ozSdb4IQmRThmnG
b2CrChEC5azpaqoyAU07kylZqj5xQiEQrXTID//MvH1Y+8uI+36MORGCA8co7HDc46kb+feuVLlS
81yH2UYo7QRJSQYs0FIBNOezx3v/3rLZr9h7IY2yC1LJpKLEyW7iHL1FW8hhMDEK2EhgrgA+r/ed
qy1zzJ/DHeelpDsiOHdQXw7ZefmJI6X+h5ym5jklbt3k1vi83L0XFq8iADIXS3Ses5dTJ+PCD0w=
```

**Comment by carlosefr** [comment]
Hi @miguelpduarte 

Can you please regenerate both encrypted bits using the updated information in the README? The initial public key was wrong and has been replaced with the correct key, plus the OpenSSL commands were updated to ensure (some) compatibility between versions.

Sorry about the trouble.

**PS:** If you have a preference for t-shirt size, we'll try to honor it if we can.

**Comment by miguelpduarte** [comment]
Edited! :slightly_smiling_face:

**Comment by carlosefr** [comment]
Any preference for the t-shirt size?

**Comment by miguelpduarte** [comment]
M please! 😁

**Comment by carlosefr** [comment]
Hi @miguelpduarte ,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to org@pixels.camp. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (carlosefr) on the Pixels Camp Slack.
