### ISSUE TITLE
Pixels Camp Forever

### ISSUE THREAD

**Issue by mjamado** [PixelsCamp/pixelscamp-forever#60]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt in size XL (preferably bigger, 2XL or 3XL - yeah, I'm fat like that).

This is my public proof on social media:

https://twitter.com/mjamado/status/1306349347462959107

### Encrypted Name and Shipping Address:

```
U2FsdGVkX19ARIDYEPkM0q4pbn73RacI8GyifSazX60/pXxa9+wgWG9/ZeNby+B0Kz0XpkHpByTM
TJdfyNDq1b5zjhkzLSnVFyscABgRJPlckgB1QOKo9l7WBhqvxSBM
```

### Encrypted Shared Key:

```
ewR+EtfGd/PhDz1wUZKE3cImHNsVe7JiqAqp9mE3T6jJ5yjKBT26nNqEU/EXsb8aMMagZ9CH5w+6
y+y4wiZa3wS2kgLFENBuYeA71xLAfZGXpOYve73Q2hOLqyZ5HqKbGBV3Rdx/fQ+BW/5AuNMkdibf
cd2eY7TWxeYuSGFQBug51xcgXgisupVEot1UzKDDAGd1+i4nfZvFdSsfmxpfjkWs8VPt0+Xut7c+
faicFZ5FlMaCuUmfjyLtkWVyvnC04koa9iyQs6SOkPSF75AT1jqtykVRGhuMFIgdg6+hxV8o6jwi
Fpk4UBauOndwIjTWMnU5qOh8b6ebEXrfQF5gVWGsC6dFRtf3pWl5F4hQKiPeP9TX2DjaTyUASBRz
MDQX+NYXPPQkyWNyRtkwzEaogb0GzspFV480VnHbXWOW7DHxlqkYj3AXdX7AqRfHcvipl1EbWRUP
zZTTBXmBe6LPCbXT74svkm7oqLHz6O1St7fIsHxVxUzClUDFtDnmMEIzPc1Wy+1PH7/E0HMaB95G
aEufBt7X9tK9Uf1/KqVQTvO0eZlGUHsShlNk2m3pKCKBImuAKM/hFlzKlTx1KkI6X80z4xM4er/t
6RveAytWo2wQVt/MGItcmze+h6AkDjLvIEwhaoAwEvrZ4EvCqbYnmeqF3yuSjRUQC3y9uB59EXA=
```

**Comment by carlosefr** [comment]
Hi @mjamado,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to `org@pixels.camp`. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (`carlosefr`) on the Pixels Camp Slack.
