### ISSUE TITLE
#pixelscamp #forever

### ISSUE THREAD

**Issue by andreffs18** [PixelsCamp/pixelscamp-forever#61]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt in size L.

This is my public proof. Youtube is still considered a social network right? https://www.youtube.com/watch?v=yDHg3st_IEk&t=1638s
> Last dude on the right, 
![_](https://user-images.githubusercontent.com/5011530/93394889-d4e2a100-f86c-11ea-8281-39d6aa996be9.jpeg)

### Encrypted Name and Shipping Address:

```
U2FsdGVkX19h8hnBrFbYqIRJGIyjZZ6HjhQx46zxrLCfV8rLNHu4rOI7E41xEkNjmAaoT2XD4Qp1GESFSMGcUpru/5XtERHJ/LoRfxXxeLY=
```

### Encrypted Shared Key:

```
tUm6AtXNQaQ0sijwCeJ1pxOTYR5fThmrCVJe5HPgCAlBGomnaH3B5mz1cEbZG4RHLCyyJjAwcKib8N/XEJPzMC64TqStqKNWHf6ZToSGk97MRgSZg8N08tcuajoL+Lln64g/cxfm7+vwHUNc+bSgQGhvYEXgwCwY647a9ja0RCq3tTvoTQCSt9OAtOZpIKU7nl0I/pRoRIFdKDpvzYzUsno50SNrm7oHWzg1wex7nsl57lwDOa+Fyr2OwgAYqNNoCKO4oaCEu6F1lMp7zqUBtXMLxRZNhjQUcCVvxZ+Av4c8kJGOhF4SpGHRQ5Gg0Dqx8C7u40zv6ulFTtMbjq0Nvd52CMTljdFffmZejbCwH391Ehcwbh+fxDirET4v37ldTJMrPd9fRsM5NPi9+Bhvb349al43aUNKB4xsVcB/A79JQNVFTch3YKi5RszIMRsviYst1OEeYlQ4tNm/WiizB4ncjWkdGk2cq9r7o4phuPOOlE89MtMImC9breX3nNrxTHsRvzuHJot0Y0dACXT/obSaYDvPUjMazfZEuIzgGK0ukLxscN5mXTy8TKv0YpvIrabU6alDCG8iZMb/vdhQo+cHKP/07C0WReFAdMPV7zs07RxactMpCMRO0ShAnOnf0D8lbr74oRS0dDYEjd9dObvcUYJJCMK7XugcqA+pIv0=
```

**Comment by carlosefr** [comment]
YouTube is still considered a social network, but maybe we should get the t-shirt because that was posted by the Pixels Camp account. 😉

C'mon, just do it.

**Comment by carlosefr** [comment]
**Reminder:** The deadline to apply for the Pixels Camp Forever! t-shirt is Friday, October 30. Your submission must be valid by then to be considered. Please see the comment(s) above for what's missing/wrong.
