### ISSUE TITLE
"we'll always have Toulouse..."

### ISSUE THREAD

**Issue by reaperfromhell** [PixelsCamp/pixelscamp-forever#62]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt in size M.

This is my public proof on social media:

https://twitter.com/reaperfromhell/status/1306442739429539840

### Encrypted Name and Shipping Address:

```
U2FsdGVkX19FyAZ+at+mA33WgnIpnMQ2ojqnosoGA++vBMOtkRondAYgD8FH48H/u7mGU0HLvoDh
9w+LCJD3x+aP64Y9StQJlxRDqZv6NA3ozP0yc9653jLZ6IJnbdBM
```

### Encrypted Shared Key:

```
hd5mocTpkuTuyBfFG3nA3U875q+oRUvYOzmvXUUoaOGnL/ZJDnmbur06oI9rRfUjVamZR7xnVlvq
YNgPDenFAPO248YTuVThWxmVyQsmkJ74c+Rb1KXQhMSKmY8aGygFtDe+V15uM3jXxkFqCqxS8UDO
MGCz+MKKTw4Pwip84gtVv7ayHP2GHY7kG13shhxD4leYl+oBwijSlv0pq0Fh4XnGtdhWuOP5l1/O
ttH7cKkP2GiQPqpzMz6a8xPJE4siKfGtsx0EVmcV4hP0VkLK75Q5nKZGUxyi/9TLm8Prlf241mPn
7onD55tNcMY7J6VhfKOmqUG1NuCItn7btYWWYiCH8CLH2PcnN/vFBd4u2w4XvvIPsEKH7soeSoWC
wKz2hz2n/SOya1OpluJS5lQhpMREIJGIYBCO7e1igYfouyN2L/W56T+D1ASWGblT8pwsNVzR/eXC
Fbhy/z3Wr+u+oy9XHZrKS7yW2Ah/T5Kc688wNsZS1ibiHiuYzsmD685qF0KpFa+EkNYNxURzV3gt
8J1HrdcVwatU4MWtqPCAENqXXn6mOOZeZiJXkjU/6W6FlO0G4t0xvA0wUWkPyC1fAovwtdlPM68z
mkWSsyNKGcZTjJKEke9iSO/l0M46GUBOI9nZ8RuSN0lPO6gYqLLsr4Ar/GJ+7RL0dryJ1IWV/GI=
```

**Comment by carlosefr** [comment]
Your submission is accepted, can you update it with the encrypted bits?

**Comment by reaperfromhell** [comment]
@carlosefr Challenge completed! =D
Thanks again for the awesome job everyone is doing!!! \o/

**Comment by carlosefr** [comment]
Hi @reaperfromhell ,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to `org@pixels.camp`. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (`carlosefr`) on the Pixels Camp Slack.

**Comment by reaperfromhell** [comment]
forgot to mention... it has arrived.
Thanks again for the awesomeness and for being awesome at delivering awesome to our doorsteps even during pandemic times!

Awesome job everyone 🥇
