### ISSUE TITLE
Limited edition t-shirt request

### ISSUE THREAD

**Issue by nunomorgadinho** [PixelsCamp/pixelscamp-forever#63]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt in size L.

This is my public proof on social media:

https://twitter.com/morgadin/status/1306489164850892800

### Encrypted Name and Shipping Address:

```
U2FsdGVkX1/aQ8507Bp7OHNhbHQ9REE0M0NFNzRFQzFBN0IzOAprZXk9RkM5QjkyOURDOTgzOTNCRUY5OEZDRTJFNTU2NTY1QzM2RjVGODQ5NDY2MUEyQzgxOEI5MDQwMzQ2MTJFRjk5RQppdiA9NDMyOUVFMjE1RDVFRDg5OTlBQzhBN0ZCQTYwNDkyM0MKGwTsToGPgghHie2hOKSy5xs502zk5A3u6tpkgKQW/0HqH71uPRGoqpW1WIKKaV5wKS4WFHoTJVhypOai9MtziJjNrA4ZKjX9lCGCuXd4Z8o=
```

### Encrypted Shared Key:

```
ERMhqq7F5a6GsGBpJBTtgbU9w2KLlt1o7E5SqDzYEKI1FN/LtuJW35ezSOqK8SLXqQ0SHZxVpSLVzCpaxMgvg8d2pYIzdPIQK/ffx/FKjutEwwD35qUVcJqbu9o8PrkbChb02YehpvnFDnQHfa/S4D2qSeY8ZrdtzttFSExhurBn1VuV9c+2VB4AD1Q9t2pEBhb7LTeNlVujQFah8Gg1Q5j3l9HFzfDhP6wwfDhQzzB3yPlk2d+kXD9i6t04AN9W5z0x+GwD8KJN5D00x9qOnF5PtbLRrg5Hn6f1nh8Hd7JjKzZNDd2OGAvWwpK0GQk44xIatMWVAAhIHHfoz3nZ7I17Xaj7WbquIhWd9ubuGKhnZbWPjjD3mIuJLNTPAD0hBtrvreV2gs6PU4Yp9H3h4qDYt5Fl7JQggBp8FvkCaTroEOcT0X9Y/ye6kjyaw5HC/i+dwrIpfV+ueH9Cmb2f5EiCfhXGndWjhJc6DzBK3ZLDQs+TRFUQI0kx7/qMxfiMfSSK0EybMse5lN8EgfJ803Q0vsugKzqaX0BSAaQnGwUEWg7O44yDRa6BBAS0Eg9yLNSd0NWrl7aUaZ3bjLx5Q4+E34m60qEMwuijmRrKS5DNZ3/aGhgUzO3dMN4NxtwQx2S3k6O+I4qtflEQpEe57ohFbnFNZIVjNYJQ4L0OWUM=
```

**Comment by carlosefr** [comment]
Actually... this should be about Pixels Camp, not Codebits. Even though they share a couple of organizers and spirit, the Codebits brand is owned by someone else and they aren't the same event.

But we'll accept your submission anyway. 😉

**Comment by carlosefr** [comment]
BTW, @nunomorgadinho  there is something wrong with the encrypted bits, can you check?

**Comment by nunomorgadinho** [comment]
See now:

Shipping

U2FsdGVkX18NL5Xhgy2abXNhbHQ9MEQyRjk1RTE4MzJEOUE2RAprZXk9MTRBMTJCNzA1M0MwNTMxQTUzOUE3NTA3RUU4Q0FGNEQ5QTczNzlCRDk3M0UxRTZBOEVDODM2QUZBQzhFMTQ5MwppdiA9OEQ4OUU5Njk3NDZGOTU5N0EzRDQ0RkRDNTlDODU5QjMKzyLCk0JfdHLwiLBqpqNexSWgweCaAV1dicQgmEbqH98CR3k/sA4/96Gf+VH6ccqAAAYTi4dtE+mmurnsfKOp0r14J6bo1tL46UKd479lQqg=

Encrypted Shared Key:

g5dYGAAw1RHwzJA8n+YKX77Z5VuHCXnyVBXpeWA2jDNF4Tjbn5yDaIr+tzb5B790tuSdHCPxwRQybtbM4L5O3UzLJEgj3CKAQUREBTZRtWQrgwXwb/NdqEz5fQk/nSnxWpbqPogwTVfpF5nZq1FLP7uINWi7RVWzrWHEIeC+hMalijFa2bTPqPR9VkX7sB1EtTyvKV6vr9U5NHUP3mYl6sOR4eXek1M9KuUk5zUYX2c8jBL/Aa22J7L6P8De9c5EEuo9bifm3mPw71TLqewRqx4S/Wv2C3bd/v2xboiNWK+fLi0iPYbupryZjJn3ryqbSk4j9Bz9Ub91ZPofXfLrlP8ZERYy9+YIsZPIw6gEgYyt2xrDoWL15Bj+GopXxCf3RczCMAta+pAtOokQ0BsqrAO5m4QZ6nUfQoUjI3SRcLVtYBp1z7I91gEY5mtSFUCJ6d4YtuL/6C9iVgFf8ki8BD2pDkJBhGvAgasMwKDfYJ6yzFGxEK4leMzgxsK/wZgxexKW6Bti8hsXqdzMhWkFgyKaUpYJrogv5go7B0/AtnAkv5ieNnj34/Mpv+Voz19lWGraOzImwCqBDT4ARN1mW/fS5oj4lxGEDdh8lDYIPK72K7Hjb4vWs3FdZS+4FqcBsBpO4fNGiqFxY+9vQiFkTkesGnZOtXf2Aqc8CgxBbB4=

Thanks

**Comment by carlosefr** [comment]
@nunomorgadinho I still can't decrypt it. Do you confirm you're using the public key that's currently in the [README](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md) (for a few hours after we opened this initiative, the public key was wrong) as well as you're using the commands as written there as well?

We've also had reports that the native OpenSSL on Windows may have different internal defaults making it incompatible with the version you'd normally find in WSL or Linux distributions.

**Comment by carlosefr** [comment]
Hi @nunomorgadinho ,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to `org@pixels.camp`. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (`carlosefr`) on the Pixels Camp Slack.
