### ISSUE TITLE
I want a "Pixels Camp Forever!" t-shirt!

### ISSUE THREAD

**Issue by pedrogustavotorres** [PixelsCamp/pixelscamp-forever#64]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt in size M.

This is my public proof on social media:
https://twitter.com/_pedro_torres/status/1306499593266397184

### Encrypted Name and Shipping Address:

```
U2FsdGVkX1/RiIVB6brLWpSWzpSoUvD9QwZRYpjykq0olH6eJNiahxI6x/foJmFtOmvwpwQAmJR1jRqqpxSvafGtuAOrpZNyJrGsEH6i6P4=
```

### Encrypted Shared Key:

```
ORnuBtTrYUt7FIrAS3xP417f7XOzMr+gM1+RqO7x5YnO3AehIiLxsZh/xfQAsLJdS9lOqEK8Fp3FUZMNdxN0mW0Mq3bNECXmnmaTmrvcPcra6DGtphq9erbW/FRrEaW6fXtbBn3yhWKps/r7/g6F7yfEprsMFyiCOKRWc0sTgc4W6/z8xJrOYCYGduucnGrmpE9+JoBDnjgoYf0jMrhN/Xh51QylRvTty1oGhqtb6r787jVIh2Nr14bVcAhYntz1BH6zrpr1QHSXDp7I7d8loM2jFxEpil3JFsSkjU9OmTRO6BTnpoS2VI1qJrabTk65tXkdvLNqxZVAvNDIQ1fRF1zBpwWO/lMvsJTKQryy8phzvpdhxpYnncliAQ53K4wusQBOhnDZQZje+9Z0XUoF9X8ibhPzeIjm+biQww39fM4EHALuXEV5Wng/Lcp15Kq14/rD4Br/Rl00PLDBTR2gfHgEFzOlTePkxfocXgws5ly3WLKztT9m37I09Q4Cl1y4WerXrK3Res83VP2R6KDhuRpBvJFUCvVTOEtmYGQZhjk1af3KaOUfp6PeKGXPQD/8pZyGCyJUXIk1StS/3uKeFHOLirBJJwGad7hlJ5J3xwNXSTlMfhu6KMbgC/NV3hB/Cbkknd5VuZAxIwHinfjgNSfWvdWavJro/HoepeqH+po=
```

**Comment by carlosefr** [comment]
Hi @pedrogustavotorres

I can't decrypt your information. Can you please check that it was generated correctly?

**Comment by pedrogustavotorres** [comment]
Hey Carlos, I actually had a lot of trouble to generate the name and shipping address... even after updating homebrew and double checking my openssl version I still wasn't able to generate it. The only way I did it was when I used the old instruction:
"openssl aes-256-cbc -e -in file.txt -pass file:random.key | base64 > file.enc"

With that being said and for the sake of time saving, due you mind if I send my Name and Address to your email address?

**Comment by pedrogustavotorres** [comment]
Hey @carlosefr! I had issues with openssl. I just redid it again and it seems to be working. can you please double check?

**Comment by carlosefr** [comment]
Hi @pedrogustavotorres,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to `org@pixels.camp`. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (`carlosefr`) on the Pixels Camp Slack.
