### ISSUE TITLE
Limited edition t-shirt request #pixelscamp #forever

### ISSUE THREAD

**Issue by marcos10soares** [PixelsCamp/pixelscamp-forever#65]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt in size **L**.

This is my public proof on social media:
![screenshot](https://user-images.githubusercontent.com/7953349/93445253-dcd02e80-f8c8-11ea-8206-0ceaba51ef73.PNG)
[instagram post](https://www.instagram.com/p/CFOyIxfBrBu/)

### Encrypted Name and Shipping Address:

```
U2FsdGVkX18n3WdLMM05/Ph3sS8aJqu5l0nI9Ygh/AcACqSkNLxqzlpVHXCMiG9Od/tnj5pbKL4wP3Kn/yNcM20Vcz1el4nrJkDymlTzLfPU3F5R3h52aHNIC+kE2T2P
```

### Encrypted Shared Key:

```
su/3bbSmAdbNrzcIcTaADHVA/I2HLQv22KqSWhKmhu8ccd0+GyL7dLqtjw7FyyYIAZr9nLcCFQWOM0ScL7N63uZJUyLIpePta7sFpv4xrVKWQYKPugLC0NkBQQP7TbDxJnLBCLLDI7H7RGIStCW4OIrL2rTNevCQmfBzx3NEu1XJBVMSoHmaT4ri9mDKyInzG3O8ELdaKLf1AWoyRDkgw0lYUnwFpRt0gLtoj/AozmUat0rndH8ClOY8icM1fD2yMMHWJLmym3J8MEG/AGynCD7e1AtiTTO71v7HI/eApWNZYQuRrjKC9Vn9ig3pYZ+RKyATNtUAiqpkQO0ZFwLkysUpxQIZeVO0wxPelp44Gj7NA6HWre9fZPm2+/0hDENysXnB7r/uVdbGsJcp4LLq91AHvoACogbmNhFsjouZ6G6i384eYQ+JPblKd4tFZZurDMKnA6NuR8uzT3J3WMRSdCZmwpWquTQ4Er7YdcGMhlnMT8c9Ghw6mEyzVOoaGJ18SxJhRXdSqjIVFmOV6xXW2+H5R8aWlZEaoLHRO8UPK/3Au2YKhGS9qm7kpgZWQASerZa5+OhPCnNYim1IUrkQahEC5fWsXj81P9aWiy6xn+FYxaUaWbY88gVHZE+W1xpMw9Mdb2qfcVGKv5NzUjbUU6pAiRb08XLWggg1GmqTVN4=
```

**Comment by carlosefr** [comment]
Hi @marcos10soares ,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to `org@pixels.camp`. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (`carlosefr`) on the Pixels Camp Slack.

**Comment by carlosefr** [comment]
Hi @marcos10soares,

Can you provide us with the required information by late Sunday, December 12?
