### ISSUE TITLE
I want another tshirt pls

### ISSUE THREAD

**Issue by LuRsT** [PixelsCamp/pixelscamp-forever#66]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt in size XL.

This is my public proof on social media:

[A beautiful twitt](https://twitter.com/lurst/status/1306497637449949184)

### Encrypted Name and Shipping Address:

```
U2FsdGVkX1+k6twpihcQnvHf18WTwdK0Us5zmOV59JowNJms+A4CbfnX6ZlXY2w/F/J9EWRae8ts
SeFv6GaGxZVUdG81UoJmYZBdwrKgEVY=
```

### Encrypted Shared Key:

```
XvBahUufxIBZ/yexK5+AlDGBwNVt6ZYXxnBFQZmTM/cDj1FZiZK7hb4SrFvXxpfQvINTCNWpdCMv
prTx8UadI/qfNhGqkwQa+gG5jClqq4CiXgOgYl9Dullpg89xXNb+DCwNYCfu9VWhH2NYLzr2iQpJ
krHOvRMhghx2LIz2XxrbyNO/npnIlTcdrDsLitZaDDP+QL5v99+GyE6Gk1ZlVnz/iSqonuAGiKev
pZT3Ifltzirh26IzDpRUMj0vMNPUJrmJk0XuN+nmwnkE0RhoMkASekDybRlFBvV1KbPBEV2mFL73
XnuxkuwqQZz43HxtMAqwldQYBZXt3go13KW3Uv+3wKQejikOLdIK1S/rCx9YCjhkpGZdAgUMCx1G
TTpZFGNFLUDNfWCtwOj2hpsDgl5H6735SO6O7y4f+eLtYnBFvwuuaZBXyC5D9woq4dr5OtXyF6e7
YDS5CL/8BDVborqpej2EeyxL+Hz6rjDGw9qtiHqmsT6f74Hxf3Bb2F7w0ltN2X4+KxaUnfKXFkep
zKUhzm2NMjFd4/41eoU3dr/CT/GHQ18tAfYOUdYzEV1Luin++TCLr/CL445N62cnc396cUvPfJTL
nMmMdMcKC/awO+og8jajracGEReSQBCW8e1MnMsBfFwuYrOzwPdeR7wkTz5d5RiVnYGnGm64DqY=
```

**Comment by carlosefr** [comment]
Hi @LuRsT

Your submission is valid. Can you please update it with the encrypted shipping information?

**Comment by LuRsT** [comment]
Sure thing @carlosefr I will update it this week :+1:

**Comment by LuRsT** [comment]
Done @carlosefr

**Comment by carlosefr** [comment]
Hi @LuRsT,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to `org@pixels.camp`. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (`carlosefr`) on the Pixels Camp Slack.
