### ISSUE TITLE
Pixels Camp Forever!

### ISSUE THREAD

**Issue by celsomadeira** [PixelsCamp/pixelscamp-forever#67]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt in size L 

This is my public proof on social media:

https://twitter.com/CelsoMadeira1

### Encrypted Name and Shipping Address:

```
U2FsdGVkX1+V90lSzEIlYl85LtYC5zIRba3kCEVYWHZLQ2qKPQRObVLwY3NZQ9DIqObLkq0jsrY4k6DArnFG3o6S6LIP5tpimMMafhlXr6rDjalaZPZA+S1JZOX0r3+M
```

### Encrypted Shared Key:

```
bwJqwaKA7a7trQZzbtsw35Q38t6XAvbVOdm6aZs+62DFyiEwYgHzKvCjqMjzIZiGhUUI9gMTEkUlku+HdGwwuHTn4iAahlIqTIS5DxZikzQdwWcF5P+gPjeyPQiJDQTHHuLDt5DO7bfEkJVPLlq8YCGRtezzjUFzOXEC+Xpjk5Hdz4HbX31J0dcVNKnMz1BDAE2OU2jxvjrZUFCAE4NlVAQUbYKBQLepFHdR2NQbooNrhc0K/MR36WHI0MBxKXGfbQKxGq/rI13B4gcoQvbH67McOpN0buk/qbsY+oplLm9Bwf4OQbrBmtPvvaBmTMI68Z17mweAg5RJUHLRRMOJZ5igAditxmwGIDBkgumOldxfZEr62OVHmqnU3VDeXCTO/tzC80IDo9kMsJ7SAT0bw63VoYQZm/QPtDCh2NjRfWpMbaDqdK1Hi2PzG/KluPYsoeB7jDdkJu0+S8haswhaSOJpmOha3xCnE2s9BTYdKNzlgEN82oR5bz9h/Fk4D2p88wCsMCirX8gzIWbxzvBJZo49iLyhEETxyKQ9t0ZUc66giFaAAvOS6HH5FWPud4H5SXfuKUsbyDA3bNPEknazdCF3rGa5bGvIk7x7pb1MOojLrDbm95vk25NLuFUK0/Oroql3MzysxPOOoJ0E9G6iCBdNt97QqLo5tBm6WKmHfJ8=
```

**Comment by carlosefr** [comment]
Hi @celsomadeira 

We're unable to find your username in the Pixels Camp database.
Also, the link is pointing to your twitter profile and not a specific post.

**Comment by carlosefr** [comment]
**Reminder:** The deadline to apply for the Pixels Camp Forever! t-shirt is Friday, October 30. Your submission must be valid by then to be considered. Please see the comment(s) above for what's missing/wrong.
