### ISSUE TITLE
Supermalvo’s Cup of Tee

### ISSUE THREAD

**Issue by hypermari0** [PixelsCamp/pixelscamp-forever#68]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt in size L.

This is my public proof on social media:

> @pixelscamp was my first hackathon ever and the debut of @taikainetwork in 2019. I'm sad to know that it won't happen this year, but I'm sure the next edition will be as memorable as my first. Here are some pics of my epic live demo crash and other moments #pixelscamp #forever

[@ Twitter](https://twitter.com/marioralves/status/1306321042101751808)

### Encrypted Name and Shipping Address:

```
U2FsdGVkX19Svb98GPTexHDvqImKUXbAyaIXEpe0qbxWxnkJNtPPZPFpsdFZ+PqhUsO+rnloZ7xB8dxwSbc2KNGkkU52iZpqgpAGKxdT/mEtKgBCR8QdSyZVNOTgFr8r
```

### Encrypted Shared Key:

```
aizuJ1phYkl/OrAaNYlAyKsa+jm198S+lE0D4qeNvcC6UIA3940bdAi0Tbn4qaoO+Ojjk/E2vOxK8ReC6URMduqDxFcfGIbsIjKeSF/EHmVwdIOMCfkbLoseV7Wvi0Ui1Do12ZD9Oz7UOY0FRfhC6AdAnv6l+204sLNWHSC6WV2MZ2iBw3PLdwYWDbWNqXDPWBXLj67TTTpkSxnIEfsT4bR72lBLK+PxJhsoyXG7F3giZc3dMvfmhB0KFxBWT3zRGaAzutUnZHqhOBGPsnMGM1ATRjrssICUQYrPUrHjYIStyVIAp1rdhQya1RsD+FwHRI2KFgY0Ye+knXerbje40mG/S3JT/ZytfpOVOjlXFGOAd3uPrlboqFY1CH1BSE1PbiJjO6RDOxm5mOUNdcKo+LGueAueKavPyJWIxT8ji+cZu6SmTAbaNVsyYAS9ZWKxVR7ZbKzOIyyM2zuXCXEmGVehmHl/5KkgCC5Wjgup8jrnXiy0tQIhfeGC5o8Ki+gKItMInYsDIaBbkhK+BaMJ3peBbd0GOWlrwKUkEvgSWvdcIp1zFTjQTOen/rZhsR461p+WUn0Vc3IQl9ejPQwOHY17LqGJ0VUoDJDE2spMTlPEnmm+omsfiJaZ/VF5UJokkLbRipFJbm/q/fui4OPz9S7PuPePGIRTed5WOcT5m1o=
```

**Comment by carlosefr** [comment]
Hi @supermalvo,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to `org@pixels.camp`. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (`carlosefr`) on the Pixels Camp Slack.
