### ISSUE TITLE
My precious t-shirt #forever

### ISSUE THREAD

**Issue by diasd2** [PixelsCamp/pixelscamp-forever#69]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements], and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt in size L.

This is my public proof on social media: 

> PixelsCamp V4 was canceled but I'm always proud of being part of this family! #pixelscamp #forever https://t.co/Z3nABeObqb

https://twitter.com/DiasDaciano/status/1306315448800219136?s=03

### Encrypted Name and Shipping Address:

```
U2FsdGVkX19WhClCCSMfmnGcsVpSSvK0wOsddzaJUbjgI5lW5lp0LFITjDvj8eZYur3+D3x/xsSRdCSZYUQxTVLDrDdP9Wgj56a+J7VQuFQN9BcS+kF2ao5JL12oz6sWiN2T9+UIISt/kilBV+7O7g==

```

### Encrypted Shared Key:

```
iHC2j2b8/kLYWKZV1LSKjoTJ9WFeTUXbrTt6m7zml/nzILOWX7JygpKBn3m03ISwkL/keZNcsSRE5cibf+4vBSRYSjdiGJlyA3YydonOc0gQ7OpO+xwhWE77FxgQcZTZPMVsa2F1WqC3q30tKb2MRu4pNcq9CZM3s3FDCKFRInutOysEBKYSLCNqk8QG10jkfka3wNWdj/KDZs4qilQtP5wwkYem8s3NPpjoegHxSZ+gdgOKUYtSM4n2Kcnd+HGdwnX4qK1oiI8nvqF2glSzxxqiHq50F7xADy3CoGBDn/bmOPAuTyfHjLxo7WndyFntAyoiUy+5SCFmrYC0BjV4UVZd5z9ou9YZG9CT/nSyFdD4UqggtFOsvGloj15zHxIJWE3LyNEBjM0BGrANcKiwPBhXWe3AOwUvM64lFBusavdRrWt066r53F6Uvg1RwhzqpZTk9l/lLKPaVJ3ZXftrhsMc39yXa4T82FGACTA0mYjEisaSEJd0t8FjCe2WdzKdn+zzssqxGVpIDtUBXjV8irwoOUYzxZq15E6D1U+0pGmoHT9x86QeLqoGNRlMbEmuw4JpQfuIYcaCP7OU6i1LaZuqZE0b7yn/fJlOb14+QdhMsO9/XLTasQ3VWIm/X8WL+TlgvIWZRM27cZy40VzJa2xUk8hHt/jS9laQfPc2jPY=

```

_You can edit the issue and paste the encrypted bits later if you wish. They're only needed after the request is accepted._

**Comment by carlosefr** [comment]
Hi @diasd2,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to `org@pixels.camp`. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (`carlosefr`) on the Pixels Camp Slack.
