### ISSUE TITLE
Been there, done that, got the t-shirt?

### ISSUE THREAD

**Issue by jmarcelino** [PixelsCamp/pixelscamp-forever#7]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt.

This is my public proof on social media:

https://twitter.com/jmarcelino/status/1305461519950503937

### Encrypted Name and Shipping Address:

```
U2FsdGVkX1+6mkUy4VnZv0qUh6h2QZtqpTxEvh65/7P9Xjwdc3k4atUBX1MSJiPRaO+4buSkxOQDWnTxcngri1AzqOdF4MWTGeezf1yLoPE=
```

### Encrypted Shared Key:

```
iKL2BMxn9whnrWZcR3XY4cK7LWW00TFk4VN0voQe4A2nJZ4MjI9cuNshluA87tClvk7bCGfAbjcmfiDFcb/eKVhe8OdJ/bV7+ROduVCDwrqqfrYsZUC7wxoqRyfGpyHy+8+kYkFCSQ0yqeHHf5tGpLYMQ0LxagEN8ZlXnL/v/27Hp9TbfwJGajJS83sBJ0vQLmBAn6ig0r7HxMVduxuYiYQDxSh7TkcceKBERbfnrxJlir4NyDkavIBQFbQ2z1BCwUccWih1A6aq5JuuFX4rlAoRL95JitzBlsIM8OubWX7e7ZF9VuN6lm/e4MZsCL182PqOIWrrt7IbR5BoAD9ARyVA8WJYo+GQ1309naLFGk4IFUpGagBjT3mi2xLZL3Qnm4H6wAkHAJNBVsH7wHTv9uh9WukXmV5skl0xOLWzsiFQVkHemKmiwdI6nATheCD/sAI+tMOl450Ed/CcQtMoNfxD3H4eYqNTwtblt+O/htHFGig15xiH/7V49NqF4/FOF57SjVUFWsld2/Cs0/+a7Wx/EadlcUibIeWC2pB70T7cUqQNylZ13I8H+nKHtYRaIZ159wOCajDYHK0PhYpKprH4CPeBju4FBRj1MgAdkiMwjbbtEeFF4B9hUiXXJY8tkZFxCrJohj5/V8r412jVikNzeeMK/GW5WoNBrPPfv6o=
```

**Comment by carlosefr** [comment]
If you have a preference for t-shirt size, we'll try to honor it if we can.

**Comment by jmarcelino** [comment]
Size L would be great! Thanks

**Comment by carlosefr** [comment]
Hi @jmarcelino ,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to org@pixels.camp. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (carlosefr) on the Pixels Camp Slack.
