### ISSUE TITLE
#pixelscamp #forever #oneofus

### ISSUE THREAD

**Issue by psenough** [PixelsCamp/pixelscamp-forever#70]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt in size L.

This is my public proof on social media:

https://www.instagram.com/p/CFP6k04pbVe/?igshid=1vghw5i7foqod
https://twitter.com/psenough/status/1306366955763437570

### Encrypted Name and Shipping Address:

```
U2FsdGVkX19Nw3YJMp3GCwrTC6c8YIuP6zdTcIz8p5pSRE+4JkblzdF8ZSXuN/8wdIajgT/JjX1j
1TCdgKDQqe14oPgd6onEBmNxv6hMmXI=
```

### Encrypted Shared Key:

```
uUF4UJ8xBmDJRmtWshtMf2oSZfK7HlHbBpUgbicUMo1IlGwgFcrGEG63vqFDcZNEogxUTcHUojsj
hZ0PEZuSHlid4Vk1CfX+ZSE99f+VXt7uiSW+cCdSQWxjxqz1cpzBMLlWCgr/DlGsGpWeKE7XPSHg
qL4GYl/go9dLqVFr+M5XSKm/CIonP+PKq54ygOysq1k3HTOkqpDaeyC1OMF1q6A3HHOwoVPRUMhg
76Oq5kJvowfqYeRUwqEtSPZPDW0A9ODSGuOvajbOnNk6Ai4U+azNqJ66f5C+8qMVq2REdTMT0RJm
oKvZRcBmSUR/TwcdQpprhTeOHBRxkU0teuFMbN2iXfeOa9dRQtNL5hSoLWHr9ufEQQqwirnHDUtG
MIit6JUDADRXoddGqt+B6HjoLJ4QaiOwtXej2vSZTxsV2ud8a+Dj9PC6jTlizKWG3pl8rL23ZIaa
u2aysQCfeYzmBjtecXR8e6am9XW5AJPpIn12pEBiRquPsi9kFkL/8gvylHI1bm1fD9XZCJqkGRhq
gcC5rnymx5KptEjESwnszgmEP6abCQ9topVE03EhqJWX2v7e6QLviu1960T++nvqb+H/CcCatzNY
3VWiNc/VNNmS85Cx7A+G5miFHqBmVKRdvkplKpNNF2R8iLQPJOcqH5vikF/cQOIVlAQ7AJbqiV0=
```

**Comment by carlosefr** [comment]
Hi @psenough,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to `org@pixels.camp`. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (`carlosefr`) on the Pixels Camp Slack.

**Comment by psenough** [comment]
sent the email with that info a few days ago :)
