### ISSUE TITLE
#pixelscamp #forever

### ISSUE THREAD

**Issue by smpb** [PixelsCamp/pixelscamp-forever#71]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt in size M

This is my public proof on social media as part of the crew helping with some spicy goodness:

https://twitter.com/loboastuto/status/1305788700446601216

### Encrypted Name and Shipping Address:

```
U2FsdGVkX1+RsA97EP5YCJ+l/c4kPeEh8z8ptSjL5VLiK7MAk5P+2K6rMuMjtA+IievJb+gM1h3Opca4l4QNeC7frPSdrfB5V1tytt4uKaU=
```

### Encrypted Shared Key:

```
Gwu4unmiPtXPD19DGFva8KE7kJ1jwU/AfzaCc+7iJDT2B4Zvvl+pQkZbfVmbPCoADhezYhxMpbj/5HGvvSRqm6rtbAKgK6r0LctIUll7bAOc9VnziQ/PbrNFTum6euwWBUMxkZshd8BiL2B45w1UYAtdU9c4vmSbaOYWCY+WnHG4CWjtnN31OVRaAiKnvermSt+BOFV1oulBPWtIu+OxWqklN98t4qfBRXRFUHf6fK0sO2pS/BlwSu5lmpPGwm+tKbAvi/CaZ5AaYEcK8GDfhkvmMjfLYcIXqDAHzM/FShUW3eobpsetNTcyTKeNVyuuiRK25HUxUxtC91y8XxoWYkWhjQuhXwuvjk80fn+kQG1y6Pf645E6dPeu2qtW2FSXeJ8MIUebsbyGhggUTV1pOzIOR4YSg3gh237843Th6aSc2ZXJh4kCdhPsI69COU0yiXzTxMVJg9CHUmcM1bcXx58opKF9IT31FK/DX7C5I2Tj2QtIqAqye8ooo/d9TYGHiPzLtYyhX2drGbL14s6zjg3vqSrsZB5YYuLka+HLzDhF+xRI8hiTxnHQEW4/0ToE5sbZsftnXZGeuwUQC8U1e0p5jOGDEKlRi2ZyMrMGYJjXg7SERxku3it9yDgD7fMu22t+7AngAoerDN/Bxef7mlTxSUFewMQ7HYC9SX58iw8=
```

**Comment by carlosefr** [comment]
Hi @smpb,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to `org@pixels.camp`. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (`carlosefr`) on the Pixels Camp Slack.
