### ISSUE TITLE
Pixels Camp Forever 🚀

### ISSUE THREAD

**Issue by nelsonmestevao** [PixelsCamp/pixelscamp-forever#72]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt in size S.

This is my public proof on social media:

https://twitter.com/nelsonmestevao/status/1307670529176940546

### Encrypted Name and Shipping Address:

```
U2FsdGVkX1/cCW5UZ2hAwXNn2Y/B3bI5OcHjYgSzXz3fJpYn/bfDtHImXp0G3/V3GCqyXyH+Pbq4
PPOsxsJ3lHZgQRO49ncJJiAzttm+Lm4SECybVrFTe2+4+eTt6impY3dY2APFf0rv+Hg45u+GikJ5
yIW/5OnfReGPQ+Bb2Qg=
```

### Encrypted Shared Key:

```
f15ov9apQGEJeg5i3C5rsHj6BYMEEREr/cldmDNAyeSNwZEG/wftoxFAOxaXVbqmSCGB0UBxUU3H
pKC9qwrfvzFJJLMMIhdOcLNVNXP82HhtxfauZsptF5Cz6luLd/G3QJ1CW7cu/Xmk8gUXJxIIrjuW
jsxvZ1wCRf3NpgyMCmHf6spPn+idyR4LZdDYz3TGzxUzVpoTikiqlC9fIcbJ1+6S9qjBwtiQ3AfS
BnfR7R0KFnrFJ8PKcR8Hr+vBPYvKas3TefQvwB1qWA/y26HaxjhYT3r1/D/bqi4wcEkrgusFBSAN
7i2ZRC1dfBxqjcB0D+ReZqL6qKEtB39tQFDLkyWDgGMpER4V2ZluP2klTC8erGCQ3m0krAM3x/tu
OwDQ+DKmsJWIHULGLyxwSMfVdb08mhJYwiUBR8zKTO7onsXJg+VByMAoPdvUzsj5wPtM70vwZYfe
ooBFGIDxwZZoIX1LM/DT0bs5Pkrzt/lV0zOWlNLcupylxU3I4hxlmVX5sR3uGNzykMZTO5Grvj7z
tneqsgJU/Dp5f/cPiuhv8ijSjtWOhRiYvJsi97zZBJhWG3tbYoXybvJYvhclNZ5dgLJbW25tcaog
St6Ag6EpngZfUiOmajSZSBzl2b1dlULQjdw7/GLXRN/5hBLXSF9mcvkUChZ12pF+wCjsOXL1cf4=
```

**Comment by carlosefr** [comment]
Hi @nelsonmestevao ,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to `org@pixels.camp`. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (`carlosefr`) on the Pixels Camp Slack.

**Comment by nelsonmestevao** [comment]
I sent a message on Slack :raised_hands:
