### ISSUE TITLE
#pixelscamp #forever 

### ISSUE THREAD

**Issue by franciscols** [PixelsCamp/pixelscamp-forever#74]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever! t-shirt in size S.

This is my public proof on social media:

https://twitter.com/franciscols/status/1308795330264207363

### Encrypted Name and Shipping Address:

```
U2FsdGVkX1/JudJLatpLuviq+4XqCO38trqRulU3Vyabu2T7TrJtq4JhZAluU9q0ZmHQP15d0qiq
O1hIANRW6S1NmDzoZTkK7lL3Lz94IrIu3Z565ltX3HecAzcaWeXq
```

### Encrypted Shared Key:

```
ZvyRznfP15hwWF/gH+ozovA+0CXYTgFWgoPbs9rDW3iiaiIRLGfEawoJDLPCF+uog8SLKN+tDZmz
fvo9Nsf0Ve9eJvgliqD5GIm/qhyoRPZ7gIwwo7156vegGjvTzcrOvpHm1xsMx03JfoGAekKZMP27
EBBZZ7YIv/z74atOzCMroY9Fo4NqhUjk11fWd1+Qn2nSQx2JcQ+blmGNnPd8yCw+okRlxy6cCIju
rWDA+5AyqUP95EHh+0ndinRfno0yYIJmREG/V/cEVC5PgHlVlKB4CpW0ZuAGZ/P6NXnsJgn+/A/L
5Fq4ikHykX4F0X6f9/WMP4CNfcJ9Ez7vZIynB7VUTdZSEAFLsqPRv3WmcNFJDpHT0T2FMTFo1ezB
0wlSQ6z7T1gbuW090cEoE456nIO4grtGXzegsJOfZZLJXGC2f/wfnJSoKJTyrCDZVeW/5C3dZfUM
CUgen79evEF++63PEA8MpygE2YyQHhbao80fti7X8Jxtosf7uK0nJQmEfKXt6vofCK0jNQBr7bO+
sA1Wbqo1HrAnmBCVUO+SiO2ggMqe8Tj9cDe93dNkw/msOCLm2/oOr3oofxf/3G+wvBvuEUzK4sDZ
A+wYj6MSnxd6Cw2xtrGQcLvzQaBDHwT2GClfZX2Targ16hUp6wb/6imuhfdktqDnUQOYoremqts=
```

**Comment by carlosefr** [comment]
Hi @franciscols ,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to `org@pixels.camp`. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (`carlosefr`) on the Pixels Camp Slack.
