### ISSUE TITLE
Limited edition t-shirt request by ricmarques #pixelscamp #forever #oneofus

### ISSUE THREAD

**Issue by ricmarques** [PixelsCamp/pixelscamp-forever#75]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt in size L

This is my public proof on social media:

https://twitter.com/ricmarques/status/1309177122188079104

### Encrypted Name and Shipping Address:

```
U2FsdGVkX19sod5zlM28Zw8AWpZm73fTjn5iMYHoIX6eCRMGWMpYhgkmku+f+AVgxm1hEg1+aHNT
WGujDLx8Y52bBKvybbInIHT5zM5yj6xREro51AuOy7BWhWptDdp4
```

### Encrypted Shared Key:

```
HAo16OVKkaUdU5QX94h+W1eRf6Cmt4J3ZWE2nEyqsmd7FVhBxy7BBrXA6XGfrRR1JIBmkGLdpAZ6
i2Nlto8FdMVF/9sZKVDeDawSH6R+BVEgSxXtKsqhCLNdLwKXTuToa3JGiVYJpAu6VABCSmMRllg5
BhBSa/NZgfxe1cn/TiBiwkwcCT7IZe9uIuYmOCpDiO/MXb1/cx+pGxT/z3pLnFU62KcxXOwcz4GW
w7ZklHu8uPHtyzw3+vAVkFhVuWHoMtJPJApitAp3X+GCCtUJ8fHpCbzF8ZAqYy4msJ7yIg8dAmhA
A4JbxKPtol0b++2KS5tQRudW3mvgY3qwzNbC5LRhqFeycgqoyJXro/I/PYfmBq5Cja7zRHXU2ov5
nSS6B6JmSzpW2kvQeEMJLVG+EM85g1fUCH0dpuLPxFBOSQhw00JmKJprGI8qjNMC5qwh0Vv2vnkC
4PzdyOBaFIXacEB79XDOu6+/v+Iy8ysPS3kCDBx29idt/eiCHAkrV95vCJibvdD09f5+88WEo2UG
dhpyQpnfH62xBrQ8cqGeeQrIiqaiMX/AJeS/1IA4jwhXVDbTVGlF4VtYkLhvLHxJTwNjvlHG+Vfm
xw4PnUCxRhmqgMjZSnus6RFdrB/jlJh/nC1JfMwDplMkJ7KMas1mMTz6dpobuq1pSByBU6uH8IA=

```

**Comment by carlosefr** [comment]
Hi @ricmarques ,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to `org@pixels.camp`. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (`carlosefr`) on the Pixels Camp Slack.
