### ISSUE TITLE
#pixelscamp #forever

### ISSUE THREAD

**Issue by AndreESA** [PixelsCamp/pixelscamp-forever#76]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt in size L.

This is my public proof on social media:

https://twitter.com/AndreAl83403210/status/1310945561227522051?s=20

### Encrypted Name and Shipping Address:

```
U2FsdGVkX18R8iv+/+/bx2lxeEAJEfkGmeuZcJSM1slyy6pVh0HeMPkxTWHDD/PMu8Pv0Uw4EkD6
D8TkUa333ItVA3dmvdNx4czjPDK04sk=
```

### Encrypted Shared Key:

```
ed6XcB/j6d3rcpGl7+E1iWfp7EeCW+jssik69PbDN0h6UuO3uKfEo1TSIU/B/8OWNPDK9jysgwub
SImtGxWQECwDZ4fh7wWdHpQDEIuZtXKscEWIeWjmKnR1NH9BcC6NaYGXDX1Fhcm2rFRuJ8eXri1F
VuiZ1qjsaP97mnA6ZiCmyI6EctuMqJRnbW2EMoVc7mGErP9zxsgULd++z4yuutrNh+i20WozhxMk
3weD7mrzBgDOBujfIe9EpENQwXTrg0TcY/u1063DldUX1CsWPVNhWUZF+SNyukse0k8zVUpcY1PH
12wkBoloSgG64DyOR9P6iWP+/v0s/wPgr4P2gA3AIRjfTsYuP/Vt32NQ24W0MeArg7HGbtng6Cc1
jMe6b3wOLkg7znshn784PnQz9unJkeXKCLMJF3GJYmyq+/9xTghmdINo6idJYHNlcM/Ot4yExa8K
Ieej0Nr2Ii//NMTAXadMZD/L1OMOeXOwgPUXGfzsf5Ee3O8EROn5mZGqmKUDu8e54Uwc+dzzaKHM
FIjONPLrv2TqYMQyEshgXKnbQTIbpgfaW8WhCKZD5NOyvLis2Yrs9nZ9XYjUktv5nefnE63+Rgh6
ZGG1D0N+L0rWzO4JqA+EkxS0mELgzdDypwxGODKZFXVCAHmGPtbKAMmz4J4iuBI1fp/J2IS6lAQ=
```

_You can edit the issue and paste the encrypted bits later if you wish. They're only needed after the request is accepted._

**Comment by carlosefr** [comment]
No t-shirt size preference?

**Comment by AndreESA** [comment]
L if possible.

**Comment by carlosefr** [comment]
Hi @AndreESA ,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to `org@pixels.camp`. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (`carlosefr`) on the Pixels Camp Slack.
