### ISSUE TITLE
Pixel in the wonderland

### ISSUE THREAD

**Issue by jmigueldcarvalho** [PixelsCamp/pixelscamp-forever#77]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt in size M.

This is my public proof on social media:
https://twitter.com/jmiguelaraujodc/status/1315991633087860738?s=19

### Encrypted Name and Shipping Address:

/pp5DdMovdZWEKKBU85h0KAby1VJhioysbxSdD5+QST3E7Fa0qyuLJRA+dS9X7pFZWH1YPdipyJCSNpFl1palQ==

### Encrypted Shared Key:
 Hello, I currently on my smartphone and can't right now encrypt my address ( rua do barral n°18 Travanca-Amarante) and key. Still possible to valid please my entry ? The rabbit wants another t-shirt! 🐰🙏
```
Replace this text with your random 256-bit shared key, encrypted with the Pixels Camp Organization's public key using the commands mentioned in the rules._
```

_You can edit the issue and paste the encrypted bits later if you wish. They're only needed after the request is accepted._

**Comment by carlosefr** [comment]
I think we're going to need a name and postal code in the address to make sure it doesn't get lost.
If you can provide it encrypted, it would be better. We'd rather not have clear text addresses here.

PS: You don't need to provide the address right now. Anytime before October 30 will be fine.

**Comment by jmigueldcarvalho** [comment]
> 
> 
> I think we're going to need a name and postal code in the address to make sure it doesn't get lost.
> If you can provide it encrypted, it would be better. We'd rather not have clear text addresses here.
> 
> PS: You don't need to provide the address right now. Anytime before October 30 will be fine.

I used a online tool it's ok? got some problem with openssl. I encrypted my adress and name in a online tool, hope that works. @carlosefr

**Comment by carlosefr** [comment]
Assuming it's truly _encrypted_, we cannot decrypt something for which we don't have the key and not knowing which tool needs to be used to decrypt it.

The method described in the README should work with any platform, and we can try to help if you tell us the error you're getting. If that fails, you can also encrypt the address with our public key directly and skip one step:

```
openssl rsautl -encrypt -inkey public.crt -certin -in address.txt | base64
```

This should work with whatever OpenSSL version you have.

**Comment by jmigueldcarvalho** [comment]
> 
> 
> Assuming it's truly _encrypted_, we cannot decrypt something for which we don't have the key and not knowing which tool needs to be used to decrypt it.
> 
> The method described in the README should work with any platform, and we can try to help if you tell us the error you're getting. If that fails, you can also encrypt the address with our public key directly and skip one step:
> 
> ```
> openssl rsautl -encrypt -inkey public.crt -certin -in address.txt | base64
> ```
> 
> This should work with whatever OpenSSL version you have.

Got this one, already put the public key in a crt file, write my adress in a txt file. @carlosefr 
`$ openssl rsautl -encrypt -inkey public.crt -certin -in address.txt | base64
unable to load certificate
6972:error:0909006C:PEM routines:get_name:no start line:../openssl-1.1.1g/crypto/pem/pem_lib.c:745:Expecting: TRUSTED CERTIFICATE
`

**Comment by carlosefr** [comment]
`no start line` seems to imply something wrong with the `.crt` file. Check if you have the whole thing, including the `BEGIN` and `END` lines and the line breaks are in the correct format (DOS/Unix, try both).

**Comment by carlosefr** [comment]
**Reminder:** The deadline to apply for the Pixels Camp Forever! t-shirt is Friday, October 30. Your submission must be valid by then to be considered. Please see the comment(s) above for what's missing/wrong.

**Comment by carlosefr** [comment]
@jmigueldcarvalho We must have the missing information by the end of Tuesday, November 3 for your submission to move to "valid" state.

**Comment by jmigueldcarvalho** [comment]
Rua do barral n18. 4605-414 Travanca-Amarante. I wasn't a few days at computer, only on mobile and couldn't encrypt, still valid in that way?

**Comment by carlosefr** [comment]
Yes, but are you sure that address is enough to get the package there? No city?

**Comment by jmigueldcarvalho** [comment]
> Yes, but are you sure that address is enough to get the package there? No city?

Added. Thanks for all Carlos, and sorry for some inconvenience. Good day.

**Comment by carlosefr** [comment]
Hi @jmigueldcarvalho ,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to `org@pixels.camp`. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (`carlosefr`) on the Pixels Camp Slack.
