### ISSUE TITLE
/me #pixelscamp #forever

### ISSUE THREAD

**Issue by caneco** [PixelsCamp/pixelscamp-forever#78]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ **t-shirt in size S**.

This is my public proof on social media:

https://twitter.com/Caneco/status/1317869679474597889

![image](https://user-images.githubusercontent.com/502041/96421324-8cf9c580-11ee-11eb-8061-be7912bbabf1.png)

### Encrypted Name and Shipping Address:

```
U2FsdGVkX1+2RYxEF6iG7c4gmQlSX5WPG8CGbFgqBGlXk4sDB9LvTEX9DgFUF7m+XeUjWmmeCFxUcURY9q/q3uhL0dqV0QFZI3k/Ea6/mFXQMJeFlQQrSZS5G5YAjWjtfgx7ZNxGxVhi+hLfwpK3UQ==
```

### Encrypted Shared Key:

```
DBtpIB5W5J7cx5sb5zieBnhuDSMV9UiSaB08ZzX0IpHGbC5KJfsoPCeArwUVECbEG6HwJ4v4KiNZhiKo79eHId9jveRpD2yLXjeY0bbn1phJFDVLwQheYiJQVFybMHB2vOwIiI+SiP16OWjd7U1fgyW320xIFE7MCWqeX3LzQCW3c4SeuSAUGVaYaFSnmZLQeesl/yvcOb0U99cKjvgwben0t9rlR6ytHDSDZNUucy3jl+fjEhNLSGAycmgOnAla8KDg6egRdImEQgMetTo7FMsuise+sxBix7q8c8FtXHuGaj28pFdfo5Ff1fsVWzEib+W+NZ+ZPaK6ppl/ymiBb+vXKPwandV6eVfbDJrne/HaUbUSSbSiISvf4UgC+LqeoLqk84EgIUluNEmCz5LmhfSbm7h7CyI77zvtcfhlzKxdd3Ud8Z0ik/waL5eLVXCvYsJzrFjuAgEb4z7eEhdD7IuqaexwPO+eCiw1Uzva9aJynf5gTHxImfhWFBw57/a6yxeu+QMiafD9pXhqCtObClyY7voms1YY5bIiLX5NwSZhOONa/RrpoujmH3XnQ/5V/H+abtYPO+5I/QFQ6LfVZS62PLcqKmHAuZ2/x+iGex2K38/kZbcJFy2C5J5/zx7C7+1Mxc9LV9Pt2phMmsAdoU3JzsPkOwXqaKSQo9wfGJA=
```

**Comment by carlosefr** [comment]
@caneco There is something wrong with the encrypted bits. I can't decrypt them.

**Comment by caneco** [comment]
@carlosefr updated 👀

**Comment by carlosefr** [comment]
Hi @caneco,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to `org@pixels.camp`. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (`carlosefr`) on the Pixels Camp Slack.

**Comment by caneco** [comment]
@carlosefr just sent you a DM on Slack with my number 🤓
