### ISSUE TITLE
Pixelscamp Forever

### ISSUE THREAD

**Issue by snot-dev** [PixelsCamp/pixelscamp-forever#79]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt in size M. 

This is my public proof on social media:

https://twitter.com/snot_dev/status/1321158673801093124

### Encrypted Name and Shipping Address:

```
U2FsdGVkX1+1Tf+Nq2ZyR1QYuH9kk107n+17WCUphd1fuL1sOuqDdR3KicOp3mAfHYiWSpyrZ4NEFMx2ZQNJU+yCZuOLfR6nGKU2XUDZ8LWfv0uz+omDiM6Ag33ra5kQE0QleVNP7JNYjBE/SNhN2Q==

```

### Encrypted Shared Key:

```
elNtcPJ9MHCjR2dFd91BJA/EXG+emKNqEhGI22tTjSXmOhfoHOTalnN2WpYJoE3C+JBypCw7fbhQ5UKDNjTyHpgtGePidwR26KurEmORfzLUdzWbEwFsHycg77blCqDInFJrjMZ9Dxk1cqsAFyRYjfEVDJV2COFSm/xakjZ958KtHirxv+ecTxaRPnMl3HLQDHKl8gT66ROdFGLoU5/P2ftE7y1AHdz9qNAlKoL0TY2MtC4hm9HR/PuN+k8scvGNcCidfGUdTIdAZhZHpITfk8HIktUKu3i4NEtDHpnEvX1O/5Ki6YWPcRXxg83iPJMEOTfHWrforRE1hSAiL4JRhtunMlaTK9OYOh3CuBpuYmdK9g/HzL5JKEKOtYNqvTprIkjVrIOnn+bsgBv7NC3dWFas6KtXYSbEh/5pIvMdHGcxOR1oTNU265iTqguyErcss/cEHz928fVLfXZJMmt7Vok1At18T47llLhmHl6OnQcPm1wZaGhZaWI+QZIUwfKIGd224/4YYCCBJvYUysCZOSwm1Ts3lTFGU+mKjmiwTh+hZ33AWEjiTBW1GiCzyF3fmUZuMj23t/7ZNAjPj29nNOqDQ49f6uXVXrT5o8jWd08JDmdYemRRcfRzU8FhGtVsF0g0jjpeuXGWeebhjDCy6r/ukAVqOeRNOsTxqGwp8Zo=

```

**Comment by carlosefr** [comment]
No t-shirt size preference?

**Comment by snot-dev** [comment]
Edited :)

**Comment by carlosefr** [comment]
Hi @snot-dev,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to `org@pixels.camp`. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (`carlosefr`) on the Pixels Camp Slack.
