### ISSUE TITLE
Pixels Camp Forever!

### ISSUE THREAD

**Issue by anjosc** [PixelsCamp/pixelscamp-forever#9]
I'm a proud member of the Pixels Camp community, I have read the [rules and requirements](https://github.com/PixelsCamp/pixelscamp-forever/blob/master/README.md), and I believe I qualify to get a free _Pixels Camp Forever!_ t-shirt.

This is my public proof on social media:

https://twitter.com/anj0sc/status/1305459488267304960?s=20

### Encrypted Name and Shipping Address:

```
U2FsdGVkX18L7xHCE2bBPkF1Xp4NyYu3/Gy97zyGpcss5v5WGVIeBMxgGL3n0qywZrmPbUhFbp7q
bvBswfUJjQ==
```

### Encrypted Shared Key:

```
CZAWLfs49Qn5XKWIs/Iw4SqZdf9Ck9YqgmSR0ku2gp0YasfzTeh4v9u20ei2hAyrV88z7kSMliOq
V5fnpWr9pqgaXgLpaFZFj2oHYhhrCedkC93X9W3CLS7BnTuHA55l0CI4BS2qtLb5Ti3msnlvF1KQ
K68tcNqDIGZhDbobxwOtwP839wJgcjaza4+wjQBld5WkdSxro6740/frH62Vo0O0sQ9Lt7AQX/4k
A8JLW28t9hialPWOOUERTVQ/7fFivSPitHRTFbHNYlEOsPYdvSO+h9s5LQUR3YdoLmfTSUH2+9O5
fTVj4mBtt8oIf5TFg5ZrAPNlaEMidIjKePpTyW+ou9k2QGPqKQ467rMi/tanfHjsjDbrWfZHLf0g
CKmNoo9dSr4bvyU8fcw2Unx7+lLZhgSxLw4oD7PHn6UMP4Jx4iaY6A/ecU1k/qsC0Joz31uJuo49
ID6N5Th3FW/R3e9bBuFj0AFDRvoU2wwhc/LKP4RCAdsYxnfNhNKBl9U9dt0382NxFymsTEAB5X03
UuGO4BunLuAgkDsCKuHdDm/woPnk1uakwHPYZCoebjfx6/xGNZfWCoiex0ASzZm93nPpJjLzFfEt
xdssuqBYEZqWQ4HnLbjYEN5/3pQvpGNQkWP+d+IFZdQ0ga7jpZeXl5IRTfCsQO1B8q/bVzHuWCU=
```

**Comment by carlosefr** [comment]
Hi @anjosc 

Can you please regenerate both encrypted bits using the updated information in the README? The initial public key was wrong and has been replaced with the correct key, plus the OpenSSL commands were updated to ensure (some) compatibility between versions.

Sorry about the trouble.

**PS:** If you have a preference for t-shirt size, we'll try to honor it if we can.

**Comment by anjosc** [comment]
Hi @carlosefr 
No trouble at all. It's done.
Preferred t-shirt size is L, but if I try hard enough I might be able to squeeze into an M :-D

**Comment by carlosefr** [comment]
Hi @anjosc ,

The parcel carrier requires a phone number for the delivery. This needs to be done as quickly as possible, so you can just send it via email to org@pixels.camp. Please mention your GitHub username in the email, so we can match it.

Alternatively, you can send a direct message to me (carlosefr) on the Pixels Camp Slack.
